/* Fixture-driven parity test: loads farm-c/tests/fixtures/agents.json
 * (generated by tools/export_agent_fixtures.py, with the real Python agents
 * as the oracle -- see that script's header) and checks every recorded
 * (scenario, agent, method) case against the C port's actual decision.
 *
 * Also asserts the three control-agent vtable identity checks described in
 * agent.h: NeglectfulGrower/NoUpgradePlayer/FertilizerMaximalist must share
 * ProfitOptimizer's function pointers on every axis they don't intentionally
 * override, mirroring tests/test_strategy_controls.py's
 * `NeglectfulGrower.choose_crop is ProfitOptimizer.choose_crop` assertions.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "agent.h"
#include "agents/profit_optimizer.h"
#include "config.h"
#include "state.h"
#include "third_party/cJSON.h"

static int g_checked = 0;
static int g_failed = 0;

static void report(bool ok, const char *scenario, const char *agent, const char *method,
                    const char *detail) {
    g_checked++;
    if (!ok) {
        g_failed++;
        fprintf(stderr, "FAIL  %-28s %-24s %-28s %s\n", scenario, agent, method,
                detail != NULL ? detail : "");
    }
}

/* --- small cJSON helpers --- */

static double jnum(const cJSON *obj, const char *key) {
    cJSON *item = cJSON_GetObjectItem(obj, key);
    return item != NULL ? item->valuedouble : 0.0;
}
static int jint(const cJSON *obj, const char *key) {
    cJSON *item = cJSON_GetObjectItem(obj, key);
    return item != NULL ? item->valueint : 0;
}
static const char *jstr(const cJSON *obj, const char *key) {
    cJSON *item = cJSON_GetObjectItem(obj, key);
    return (item != NULL && cJSON_IsString(item)) ? item->valuestring : NULL;
}
static bool jbool(const cJSON *obj, const char *key) {
    cJSON *item = cJSON_GetObjectItem(obj, key);
    return item != NULL && cJSON_IsTrue(item);
}
static bool jhas_nonnull(const cJSON *obj, const char *key) {
    cJSON *item = cJSON_GetObjectItem(obj, key);
    return item != NULL && !cJSON_IsNull(item);
}

static Quality parse_quality(const char *s) {
    if (strcmp(s, "rejected") == 0) return QUALITY_REJECTED;
    if (strcmp(s, "processing") == 0) return QUALITY_PROCESSING;
    if (strcmp(s, "standard") == 0) return QUALITY_STANDARD;
    if (strcmp(s, "premium") == 0) return QUALITY_PREMIUM;
    fprintf(stderr, "unknown quality string: %s\n", s);
    exit(1);
}

/* --- config loading --- */

static void load_config(cJSON *root, ResolvedConfig *config) {
    memset(config, 0, sizeof(*config));

    cJSON *items = cJSON_GetObjectItem(root, "items");
    config->item_count = (size_t)cJSON_GetArraySize(items);
    config->items = calloc(config->item_count, sizeof(ItemDef));
    int i = 0;
    cJSON *item_json;
    cJSON_ArrayForEach(item_json, items) {
        ItemDef *item = &config->items[i++];
        item->id = (ItemId)jint(item_json, "id");
        item->type = strcmp(jstr(item_json, "type"), "crop") == 0 ? ITEM_CROP : ITEM_PRODUCT;
        item->external_id = jstr(item_json, "external_id");
        item->name = item->external_id;
        item->base_price = jnum(item_json, "base_price");
        item->price_variation = jnum(item_json, "price_variation");
    }

    cJSON *crops = cJSON_GetObjectItem(root, "crops");
    config->crop_count = (size_t)cJSON_GetArraySize(crops);
    config->crops = calloc(config->crop_count, sizeof(CropDef));
    i = 0;
    cJSON *crop_json;
    cJSON_ArrayForEach(crop_json, crops) {
        CropDef *crop = &config->crops[i++];
        crop->item_id = (ItemId)jint(crop_json, "item_id");
        const char *role = jstr(crop_json, "role");
        crop->role = strcmp(role, "standard") == 0   ? CROP_ROLE_STANDARD
                     : strcmp(role, "fast") == 0      ? CROP_ROLE_FAST
                                                       : CROP_ROLE_OTHER;
        crop->family = jstr(crop_json, "family");
        crop->seed_cost = jnum(crop_json, "seed_cost");
        crop->growth_days = jint(crop_json, "growth_days");
        crop->min_yield = jint(crop_json, "min_yield");
        crop->max_yield = jint(crop_json, "max_yield");
        crop->loss_chance = jnum(crop_json, "loss_chance");
        crop->water_interval_days = jint(crop_json, "water_interval_days");
        cJSON *demand = cJSON_GetObjectItem(crop_json, "nutrient_demand");
        crop->nutrient_demand.nitrogen = jnum(demand, "nitrogen");
        crop->nutrient_demand.phosphorus = jnum(demand, "phosphorus");
        crop->nutrient_demand.potassium = jnum(demand, "potassium");
        cJSON *unlock = cJSON_GetObjectItem(crop_json, "unlock_requirement");
        const char *unlock_type = jstr(unlock, "type");
        if (strcmp(unlock_type, "none") == 0) {
            crop->unlock_requirement.type = UNLOCK_NONE;
        } else if (strcmp(unlock_type, "total_revenue") == 0) {
            crop->unlock_requirement.type = UNLOCK_REVENUE;
            crop->unlock_requirement.revenue_threshold = jnum(unlock, "revenue_threshold");
        } else if (strcmp(unlock_type, "upgrade") == 0) {
            crop->unlock_requirement.type = UNLOCK_UPGRADE;
            crop->unlock_requirement.upgrade = (UpgradeId)jint(unlock, "upgrade");
        } else {
            fprintf(stderr, "unknown unlock_requirement type: %s\n", unlock_type);
            exit(1);
        }
    }

    cJSON *upgrades = cJSON_GetObjectItem(root, "upgrades");
    config->upgrade_count = (size_t)cJSON_GetArraySize(upgrades);
    config->upgrades = calloc(config->upgrade_count, sizeof(UpgradeDef));
    i = 0;
    cJSON *upgrade_json;
    cJSON_ArrayForEach(upgrade_json, upgrades) {
        UpgradeDef *upgrade = &config->upgrades[i++];
        upgrade->id = (UpgradeId)jint(upgrade_json, "id");
        upgrade->external_id = jstr(upgrade_json, "external_id");
        upgrade->name = upgrade->external_id;
        upgrade->cost = jnum(upgrade_json, "cost");
        cJSON *effect = cJSON_GetObjectItem(upgrade_json, "effect");
        const char *effect_type = jstr(effect, "type");
        if (strcmp(effect_type, "growth_time_reduction") == 0) {
            upgrade->effect.type = EFFECT_GROWTH_TIME_REDUCTION;
            upgrade->effect.as.growth_time_reduction = jnum(effect, "amount");
        } else if (strcmp(effect_type, "capacity") == 0) {
            upgrade->effect.type = EFFECT_CAPACITY;
            upgrade->effect.as.capacity = jint(effect, "amount");
        } else if (strcmp(effect_type, "processing_capacity") == 0) {
            upgrade->effect.type = EFFECT_PROCESSING_CAPACITY;
            upgrade->effect.as.processing_capacity = jint(effect, "amount");
        } else if (strcmp(effect_type, "storage") == 0) {
            upgrade->effect.type = EFFECT_STORAGE;
            upgrade->effect.as.storage.capacity_bonus = jint(effect, "capacity_bonus");
            upgrade->effect.as.storage.shelf_life_multiplier = jnum(effect, "shelf_life_multiplier");
        } else {
            fprintf(stderr, "unknown upgrade effect type: %s\n", effect_type);
            exit(1);
        }
    }

    cJSON *recipes = cJSON_GetObjectItem(root, "recipes");
    config->recipe_count = (size_t)cJSON_GetArraySize(recipes);
    config->recipes = calloc(config->recipe_count, sizeof(RecipeDef));
    i = 0;
    cJSON *recipe_json;
    cJSON_ArrayForEach(recipe_json, recipes) {
        RecipeDef *recipe = &config->recipes[i++];
        recipe->id = (RecipeId)jint(recipe_json, "id");
        recipe->external_id = jstr(recipe_json, "external_id");
        recipe->input_item_id = (ItemId)jint(recipe_json, "input_item_id");
        recipe->output_item_id = (ItemId)jint(recipe_json, "output_item_id");
        recipe->input_quantity = jint(recipe_json, "input_quantity");
        recipe->output_quantity = jint(recipe_json, "output_quantity");
        recipe->processing_days = jint(recipe_json, "processing_days");
        recipe->min_quality = parse_quality(jstr(recipe_json, "min_quality"));
        recipe->cost = jnum(recipe_json, "cost");
    }

    cJSON *channels = cJSON_GetObjectItem(root, "channels");
    config->channel_count = (size_t)cJSON_GetArraySize(channels);
    config->channels = calloc(config->channel_count, sizeof(ChannelDef));
    i = 0;
    cJSON *channel_json;
    cJSON_ArrayForEach(channel_json, channels) {
        ChannelDef *channel = &config->channels[i++];
        channel->channel_id = (ChannelId)jint(channel_json, "channel_id");
        channel->external_id = jstr(channel_json, "external_id");
        channel->min_quality_rank = parse_quality(jstr(channel_json, "min_quality"));
        channel->min_reputation = jnum(channel_json, "min_reputation");
        channel->has_daily_capacity = jhas_nonnull(channel_json, "daily_capacity");
        channel->daily_capacity = jint(channel_json, "daily_capacity");
        channel->price_multiplier = jnum(channel_json, "price_multiplier");
        channel->reputation_bonus = jnum(channel_json, "reputation_bonus");
        channel->flat_fee = jnum(channel_json, "flat_fee");
        channel->fee_rate = jnum(channel_json, "fee_rate");
    }

    cJSON *buyers = cJSON_GetObjectItem(root, "buyers");
    config->buyer_count = (size_t)cJSON_GetArraySize(buyers);
    config->buyers = calloc(config->buyer_count, sizeof(BuyerDef));
    i = 0;
    cJSON *buyer_json;
    cJSON_ArrayForEach(buyer_json, buyers) {
        BuyerDef *buyer = &config->buyers[i++];
        buyer->id = (BuyerId)jint(buyer_json, "id");
        buyer->external_id = jstr(buyer_json, "external_id");
        buyer->name = buyer->external_id;
    }

    cJSON *fertilizer = cJSON_GetObjectItem(root, "fertilizer");
    config->fertilizer.cost = jnum(fertilizer, "cost");
    config->fertilizer.loss_chance_reduction = jnum(fertilizer, "loss_chance_reduction");
    config->fertilizer.yield_bonus_pct = jnum(fertilizer, "yield_bonus_pct");

    cJSON *contracts_config = cJSON_GetObjectItem(root, "contracts_config");
    config->contracts.fallback_price_multiplier = jnum(contracts_config, "fallback_price_multiplier");
    config->contracts.production_safety_factor = jnum(contracts_config, "production_safety_factor");
    config->contracts.offer_expiry_days = jint(contracts_config, "offer_expiry_days");
}

/* --- scenario loading --- */

typedef struct {
    const char *name;
    FarmState state;
    int focus_planted_index;
    UpgradeId focus_upgrade_id;
    ItemId focus_crop_item_id;
} Scenario;

static void scatter_double_map(cJSON *obj, double *values, bool *has_flags) {
    cJSON *entry;
    cJSON_ArrayForEach(entry, obj) {
        int idx = atoi(entry->string);
        values[idx] = entry->valuedouble;
        if (has_flags != NULL) {
            has_flags[idx] = true;
        }
    }
}
static void scatter_int_map(cJSON *obj, int *values) {
    cJSON *entry;
    cJSON_ArrayForEach(entry, obj) {
        int idx = atoi(entry->string);
        values[idx] = entry->valueint;
    }
}

static ContractRecord load_contract(cJSON *json, ContractId id) {
    ContractRecord contract = {0};
    contract.id = id;
    contract.buyer_id = (BuyerId)jint(json, "buyer_id");
    contract.item_id = (ItemId)jint(json, "item_id");
    contract.quantity = jint(json, "quantity");
    contract.delivered = jint(json, "delivered");
    contract.min_quality = parse_quality(jstr(json, "min_quality"));
    contract.unit_price = jnum(json, "unit_price");
    contract.penalty_rate = jnum(json, "penalty_rate");
    contract.offered_day = jint(json, "offered_day");
    contract.deadline_day = jint(json, "deadline_day");
    contract.accepted = jbool(json, "accepted");
    contract.resolved = jbool(json, "resolved");
    return contract;
}

static void load_scenario(cJSON *json, const ResolvedConfig *config, Scenario *out) {
    memset(out, 0, sizeof(*out));
    out->name = jstr(json, "name");

    int slots_total = jint(json, "slots_total");
    farm_state_init(&out->state, config, jnum(json, "money"), slots_total);
    out->state.operating_reserve = jnum(json, "operating_reserve");
    out->state.day = jint(json, "day");
    out->state.has_total_days = jhas_nonnull(json, "total_days");
    out->state.total_days = jint(json, "total_days");

    cJSON *plots = cJSON_GetObjectItem(json, "plots");
    int p = 0;
    cJSON *plot_json;
    cJSON_ArrayForEach(plot_json, plots) {
        PlotState *plot = &out->state.plots[p++];
        plot->moisture = jnum(plot_json, "moisture");
        plot->nitrogen = jnum(plot_json, "nitrogen");
        plot->phosphorus = jnum(plot_json, "phosphorus");
        plot->potassium = jnum(plot_json, "potassium");
        plot->ph = jnum(plot_json, "ph");
        plot->soil_health = jnum(plot_json, "soil_health");
        plot->pest_pressure = jnum(plot_json, "pest_pressure");
        plot->disease_pressure = jnum(plot_json, "disease_pressure");
        plot->previous_crop_family = jstr(plot_json, "previous_crop_family");
    }

    cJSON *planted = cJSON_GetObjectItem(json, "planted");
    cJSON *planted_json;
    cJSON_ArrayForEach(planted_json, planted) {
        PlantedCrop crop = {0};
        crop.crop_item_id = (ItemId)jint(planted_json, "crop_item_id");
        crop.day_planted = jint(planted_json, "day_planted");
        crop.growth_days_required = jint(planted_json, "growth_days_required");
        crop.last_watered_day = jint(planted_json, "last_watered_day");
        crop.neglect_days = jint(planted_json, "neglect_days");
        crop.fertilized = jbool(planted_json, "fertilized");
        crop.plot_index = jint(planted_json, "plot_index");
        crop.water_stress = jnum(planted_json, "water_stress");
        crop.nutrient_stress = jnum(planted_json, "nutrient_stress");
        crop.temperature_stress = jnum(planted_json, "temperature_stress");
        crop.pest_stress = jnum(planted_json, "pest_stress");
        crop.disease_stress = jnum(planted_json, "disease_stress");
        crop.accrued_cost = jnum(planted_json, "accrued_cost");
        planted_crop_vec_push(&out->state.planted, crop);
    }

    cJSON *lots = cJSON_GetObjectItem(json, "inventory_lots");
    cJSON *lot_json;
    cJSON_ArrayForEach(lot_json, lots) {
        InventoryLot lot = {0};
        lot.item_id = (ItemId)jint(lot_json, "item_id");
        lot.quantity = jint(lot_json, "quantity");
        lot.quality = parse_quality(jstr(lot_json, "quality"));
        lot.produced_day = jint(lot_json, "produced_day");
        lot.age_days = jint(lot_json, "age_days");
        lot.shelf_life_days = jint(lot_json, "shelf_life_days");
        lot.effective_shelf_life_days =
            jhas_nonnull(lot_json, "effective_shelf_life_days") ? jint(lot_json, "effective_shelf_life_days") : 0;
        lot.unit_cost = jnum(lot_json, "unit_cost");
        lot.item_type = strcmp(jstr(lot_json, "item_type"), "crop") == 0 ? ITEM_CROP : ITEM_PRODUCT;
        inventory_lot_vec_push(&out->state.inventory_lots, lot);
    }

    scatter_int_map(cJSON_GetObjectItem(json, "seed_inventory"), out->state.seed_inventory);
    scatter_int_map(cJSON_GetObjectItem(json, "crop_plant_counts"), out->state.crop_plant_counts);
    /* farm_state_init already set every entry to INVALID_DAY; the JSON only
     * lists purchase days for upgrades actually bought. */
    scatter_int_map(cJSON_GetObjectItem(json, "upgrade_purchase_days"), out->state.upgrade_purchase_days);

    cJSON *owned = cJSON_GetObjectItem(json, "upgrades_owned");
    cJSON *owned_entry;
    cJSON_ArrayForEach(owned_entry, owned) {
        out->state.upgrades_owned[owned_entry->valueint] = true;
    }

    ContractId active_id = 0;
    cJSON *active_contracts = cJSON_GetObjectItem(json, "active_contracts");
    cJSON *active_json;
    cJSON_ArrayForEach(active_json, active_contracts) {
        contract_vec_push(&out->state.active_contracts, load_contract(active_json, active_id++));
    }
    ContractId offer_id = 0;
    cJSON *contract_offers = cJSON_GetObjectItem(json, "contract_offers");
    cJSON *offer_json;
    cJSON_ArrayForEach(offer_json, contract_offers) {
        contract_vec_push(&out->state.contract_offers, load_contract(offer_json, offer_id++));
    }

    scatter_double_map(cJSON_GetObjectItem(json, "buyer_relationships"), out->state.buyer_relationships, NULL);
    out->state.reputation = jnum(json, "reputation");
    scatter_double_map(cJSON_GetObjectItem(json, "market_prices"), out->state.market_prices,
                        out->state.has_market_price);
    out->state.total_revenue = jnum(json, "total_revenue");

    cJSON *expenses = cJSON_GetObjectItem(json, "expenses_by_category");
    cJSON *upgrades_expense = cJSON_GetObjectItem(expenses, "upgrades");
    out->state.expenses_by_category[EXPENSE_UPGRADES] = upgrades_expense != NULL ? upgrades_expense->valuedouble : 0.0;

    out->state.highest_money = jnum(json, "highest_money");
    out->state.has_highest_money = jbool(json, "has_highest_money");
    out->state.total_planted = jint(json, "total_planted");
    out->state.has_run_seed = jbool(json, "has_run_seed");
  out->state.run_seed = (uint64_t)jint(json, "run_seed");
    out->state.has_processing_capacity = jbool(json, "has_processing_capacity");
    out->state.processing_capacity = jint(json, "processing_capacity");

    cJSON *focus = cJSON_GetObjectItem(json, "focus");
    out->focus_planted_index = jint(focus, "planted_index");
    out->focus_upgrade_id = (UpgradeId)jint(focus, "upgrade_id");
    out->focus_crop_item_id = (ItemId)jint(focus, "crop_item_id");
}

/* --- case runner --- */

static int cmp_sale_decision(const void *a, const void *b) {
    const SaleDecision *sa = a;
    const SaleDecision *sb = b;
    if (sa->item_id != sb->item_id) return sa->item_id < sb->item_id ? -1 : 1;
    if (sa->channel_id != sb->channel_id) return sa->channel_id < sb->channel_id ? -1 : 1;
    int qa = sa->quality == SALE_QUALITY_ANY ? -1 : (int)sa->quality;
    int qb = sb->quality == SALE_QUALITY_ANY ? -1 : (int)sb->quality;
    if (qa != qb) return qa < qb ? -1 : 1;
    return 0;
}

static void run_case(cJSON *case_json, Scenario *scenarios, size_t scenario_count,
                      const ResolvedConfig *config) {
    const char *scenario_name = jstr(case_json, "scenario");
    const char *agent_name = jstr(case_json, "agent");
    const char *method = jstr(case_json, "method");
    cJSON *expected = cJSON_GetObjectItem(case_json, "expected");

    Scenario *scenario = NULL;
    for (size_t i = 0; i < scenario_count; i++) {
        if (strcmp(scenarios[i].name, scenario_name) == 0) {
            scenario = &scenarios[i];
            break;
        }
    }
    const Agent *agent = agent_registry_find(agent_name);
    if (scenario == NULL || agent == NULL) {
        report(false, scenario_name, agent_name, method, "scenario or agent not found");
        return;
    }
    FarmState *state = &scenario->state;

    if (strcmp(method, "choose_crop") == 0) {
        ItemId got = agent->choose_crop(agent, state, config);
        bool ok = cJSON_IsNull(expected) ? got == INVALID_ID : (int)got == expected->valueint;
        report(ok, scenario_name, agent_name, method, ok ? NULL : "mismatch");
    } else if (strcmp(method, "should_buy_upgrade") == 0) {
        bool got = agent->should_buy_upgrade(agent, state, scenario->focus_upgrade_id);
        report(got == cJSON_IsTrue(expected), scenario_name, agent_name, method, "mismatch");
    } else if (strcmp(method, "should_water") == 0) {
        bool got = agent->should_water(agent, state, scenario->focus_planted_index);
        report(got == cJSON_IsTrue(expected), scenario_name, agent_name, method, "mismatch");
    } else if (strcmp(method, "should_fertilize") == 0) {
        bool got = agent->should_fertilize(agent, state, scenario->focus_planted_index);
        report(got == cJSON_IsTrue(expected), scenario_name, agent_name, method, "mismatch");
    } else if (strcmp(method, "should_use_fertilizer") == 0) {
        bool got = agent->should_use_fertilizer(agent, state, scenario->focus_crop_item_id);
        report(got == cJSON_IsTrue(expected), scenario_name, agent_name, method, "mismatch");
    } else if (strcmp(method, "choose_contracts") == 0) {
        ContractDecisionBuffer buf = {0};
        agent->choose_contracts(agent, state, config, &buf);
        bool ok = buf.count == (size_t)cJSON_GetArraySize(expected);
        if (ok) {
            size_t i = 0;
            cJSON *entry;
            cJSON_ArrayForEach(entry, expected) {
                if ((int)buf.data[i] != entry->valueint) {
                    ok = false;
                    break;
                }
                i++;
            }
        }
        report(ok, scenario_name, agent_name, method, "mismatch");
        contract_decision_free(&buf);
    } else if (strcmp(method, "choose_contract_deliveries") == 0) {
        DeliveryDecisionBuffer buf = {0};
        agent->choose_contract_deliveries(agent, state, &buf);
        bool ok = buf.count == (size_t)cJSON_GetArraySize(expected);
        if (ok) {
            size_t i = 0;
            cJSON *entry;
            cJSON_ArrayForEach(entry, expected) {
                if ((int)buf.data[i].contract_id != jint(entry, "contract_id") ||
                    buf.data[i].quantity != jint(entry, "quantity")) {
                    ok = false;
                    break;
                }
                i++;
            }
        }
        report(ok, scenario_name, agent_name, method, "mismatch");
        delivery_decision_free(&buf);
    } else if (strcmp(method, "choose_processing") == 0) {
        ProcessingDecisionBuffer buf = {0};
        agent->choose_processing(agent, state, config, &buf);
        bool ok = buf.count == (size_t)cJSON_GetArraySize(expected);
        if (ok) {
            size_t i = 0;
            cJSON *entry;
            cJSON_ArrayForEach(entry, expected) {
                if ((int)buf.data[i].recipe_id != jint(entry, "recipe_id") ||
                    buf.data[i].batches != jint(entry, "batches")) {
                    ok = false;
                    break;
                }
                i++;
            }
        }
        report(ok, scenario_name, agent_name, method, "mismatch");
        processing_decision_free(&buf);
    } else if (strcmp(method, "choose_sales") == 0) {
        SalesDecisionBuffer buf = {0};
        agent->choose_sales(agent, state, config, &buf);
        qsort(buf.data, buf.count, sizeof(SaleDecision), cmp_sale_decision);
        bool ok = buf.count == (size_t)cJSON_GetArraySize(expected);
        if (ok) {
            size_t i = 0;
            cJSON *entry;
            cJSON_ArrayForEach(entry, expected) {
                const SaleDecision *d = &buf.data[i];
                cJSON *quality_field = cJSON_GetObjectItem(entry, "quality");
                int expected_quality = cJSON_IsNull(quality_field) ? -1 : quality_field->valueint;
                int got_quality = d->quality == SALE_QUALITY_ANY ? -1 : (int)d->quality;
                if ((int)d->item_id != jint(entry, "item_id") ||
                    (int)d->channel_id != jint(entry, "channel_id") || got_quality != expected_quality ||
                    d->quantity != jint(entry, "quantity")) {
                    ok = false;
                    break;
                }
                i++;
            }
        }
        report(ok, scenario_name, agent_name, method, "mismatch");
        sales_decision_free(&buf);
    } else {
        report(false, scenario_name, agent_name, method, "unknown method in fixture");
    }
}

/* --- control-agent vtable identity checks (agent.h's contract) --- */

static void check_identity(const char *name, bool ok, const char *field) {
    char detail[64];
    snprintf(detail, sizeof(detail), "shares %s with ProfitOptimizer", field);
    report(ok, "(vtable identity)", name, field, ok ? NULL : detail);
}

static void check_control_agent_identities(void) {
    check_identity("no_upgrade_player", AGENT_NO_UPGRADE_PLAYER.choose_crop == profit_optimizer_choose_crop,
                    "choose_crop");
    check_identity("no_upgrade_player",
                    AGENT_NO_UPGRADE_PLAYER.should_fertilize == profit_optimizer_should_fertilize,
                    "should_fertilize");
    check_identity("no_upgrade_player",
                    AGENT_NO_UPGRADE_PLAYER.choose_processing == profit_optimizer_choose_processing,
                    "choose_processing");
    check_identity("no_upgrade_player", AGENT_NO_UPGRADE_PLAYER.choose_sales == profit_optimizer_choose_sales,
                    "choose_sales");
    check_identity("no_upgrade_player",
                    AGENT_NO_UPGRADE_PLAYER.should_buy_upgrade != profit_optimizer_should_buy_upgrade,
                    "should_buy_upgrade (intentionally different)");

    check_identity("neglectful_grower", AGENT_NEGLECTFUL_GROWER.choose_crop == profit_optimizer_choose_crop,
                    "choose_crop");
    check_identity("neglectful_grower",
                    AGENT_NEGLECTFUL_GROWER.should_buy_upgrade == profit_optimizer_should_buy_upgrade,
                    "should_buy_upgrade");
    check_identity("neglectful_grower",
                    AGENT_NEGLECTFUL_GROWER.should_fertilize == profit_optimizer_should_fertilize,
                    "should_fertilize");
    check_identity("neglectful_grower",
                    AGENT_NEGLECTFUL_GROWER.watering_diligence != AGENT_PROFIT_OPTIMIZER.watering_diligence,
                    "watering_diligence (intentionally different)");

    check_identity("fertilizer_maximalist",
                    AGENT_FERTILIZER_MAXIMALIST.choose_crop == profit_optimizer_choose_crop, "choose_crop");
    check_identity("fertilizer_maximalist",
                    AGENT_FERTILIZER_MAXIMALIST.should_buy_upgrade == profit_optimizer_should_buy_upgrade,
                    "should_buy_upgrade");
    check_identity("fertilizer_maximalist",
                    AGENT_FERTILIZER_MAXIMALIST.should_use_fertilizer != profit_optimizer_should_use_fertilizer,
                    "should_use_fertilizer (intentionally different)");
}

int main(void) {
    FILE *f = fopen("tests/fixtures/agents.json", "rb");
    if (f == NULL) {
        fprintf(stderr, "cannot open tests/fixtures/agents.json (run `make fixtures` first, "
                         "or run this binary from farm-c/)\n");
        return 1;
    }
    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *buffer = malloc((size_t)size + 1);
    size_t read = fread(buffer, 1, (size_t)size, f);
    buffer[read] = '\0';
    fclose(f);

    cJSON *root = cJSON_Parse(buffer);
    if (root == NULL) {
        fprintf(stderr, "failed to parse fixtures JSON\n");
        return 1;
    }

    ResolvedConfig config;
    load_config(cJSON_GetObjectItem(root, "config"), &config);

    cJSON *scenarios_json = cJSON_GetObjectItem(root, "scenarios");
    size_t scenario_count = (size_t)cJSON_GetArraySize(scenarios_json);
    Scenario *scenarios = calloc(scenario_count, sizeof(Scenario));
    size_t s = 0;
    cJSON *scenario_json;
    cJSON_ArrayForEach(scenario_json, scenarios_json) {
        load_scenario(scenario_json, &config, &scenarios[s++]);
    }

    cJSON *cases = cJSON_GetObjectItem(root, "cases");
    cJSON *case_json;
    cJSON_ArrayForEach(case_json, cases) {
        run_case(case_json, scenarios, scenario_count, &config);
    }

    check_control_agent_identities();

    printf("%d checks, %d failed\n", g_checked, g_failed);

    for (size_t i = 0; i < scenario_count; i++) {
        farm_state_destroy(&scenarios[i].state);
    }
    free(scenarios);
    free(config.items);
    free(config.crops);
    free(config.upgrades);
    free(config.recipes);
    free(config.channels);
    free(config.buyers);
    cJSON_Delete(root);
    free(buffer);

    return g_failed == 0 ? 0 : 1;
}
