/* Fixture-driven parity test for the Phase 2 state-mutation port
 * (src/actions.c, src/inventory.c, src/markets.c, src/processing.c, and
 * src/contracts.c's day-loop mutators): loads farm-c/tests/fixtures/
 * mutation.json (generated by tools/export_mutation_fixtures.py, with the
 * real Python functions as the oracle), and for every recorded case builds
 * the "before" FarmState, calls the matching C function, and compares the
 * *entire* resulting FarmState against the recorded "after" snapshot --
 * not just the function's own documented return value -- so an incidental
 * extra mutation the C port gets wrong is caught too.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "actions.h"
#include "config.h"
#include "contracts.h"
#include "inventory.h"
#include "markets.h"
#include "processing.h"
#include "rng.h"
#include "state.h"
#include "third_party/cJSON.h"

static int g_checked = 0;
static int g_failed = 0;

static void report(bool ok, const char *section, const char *name, const char *detail) {
    g_checked++;
    if (!ok) {
        g_failed++;
        fprintf(stderr, "FAIL  %-28s %-32s %s\n", section, name, detail != NULL ? detail : "");
    }
}

/* --- small cJSON helpers (same pattern as test_agents.c/test_physics.c) --- */

static double jnum(const cJSON *obj, const char *key) {
    cJSON *item = cJSON_GetObjectItem(obj, key);
    return item != NULL ? item->valuedouble : 0.0;
}
static int jint(const cJSON *obj, const char *key) {
    cJSON *item = cJSON_GetObjectItem(obj, key);
    return item != NULL ? item->valueint : 0;
}
static const char *jstr(const cJSON *obj, const char *key) {
    cJSON *item = cJSON_GetObjectItem(obj, key);
    return (item != NULL && cJSON_IsString(item)) ? item->valuestring : NULL;
}
static bool jbool(const cJSON *obj, const char *key) {
    cJSON *item = cJSON_GetObjectItem(obj, key);
    return item != NULL && cJSON_IsTrue(item);
}
static bool jhas_nonnull(const cJSON *obj, const char *key) {
    cJSON *item = cJSON_GetObjectItem(obj, key);
    return item != NULL && !cJSON_IsNull(item);
}
static double jhex(const cJSON *obj, const char *key) {
    const char *s = jstr(obj, key);
    if (s == NULL) {
        fprintf(stderr, "missing hex field: %s\n", key);
        exit(1);
    }
    return strtod(s, NULL);
}

static Quality parse_quality(const char *s) {
    if (s == NULL) return QUALITY_REJECTED;
    if (strcmp(s, "rejected") == 0) return QUALITY_REJECTED;
    if (strcmp(s, "processing") == 0) return QUALITY_PROCESSING;
    if (strcmp(s, "standard") == 0) return QUALITY_STANDARD;
    if (strcmp(s, "premium") == 0) return QUALITY_PREMIUM;
    fprintf(stderr, "unknown quality string: %s\n", s);
    exit(1);
}
static Season parse_season(const char *s) {
    if (strcmp(s, "spring") == 0) return SEASON_SPRING;
    if (strcmp(s, "summer") == 0) return SEASON_SUMMER;
    if (strcmp(s, "autumn") == 0) return SEASON_AUTUMN;
    if (strcmp(s, "winter") == 0) return SEASON_WINTER;
    fprintf(stderr, "unknown season string: %s\n", s);
    exit(1);
}

/* --- config loading --- */

static void load_config(cJSON *root, ResolvedConfig *config) {
    memset(config, 0, sizeof(*config));

    cJSON *items = cJSON_GetObjectItem(root, "items");
    config->item_count = (size_t)cJSON_GetArraySize(items);
    config->items = calloc(config->item_count, sizeof(ItemDef));
    int i = 0;
    cJSON *item_json;
    cJSON_ArrayForEach(item_json, items) {
        ItemDef *item = &config->items[i];
        item->id = (ItemId)jint(item_json, "id");
        item->type = strcmp(jstr(item_json, "type"), "crop") == 0 ? ITEM_CROP : ITEM_PRODUCT;
        item->external_id = jstr(item_json, "external_id");
        item->name = item->external_id;
        item->base_price = jnum(item_json, "base_price");
        item->price_variation = jnum(item_json, "price_variation");
        cJSON *seasonal = cJSON_GetObjectItem(item_json, "seasonal_demand");
        static const char *season_names[SEASON_COUNT] = {"spring", "summer", "autumn", "winter"};
        for (int s = 0; s < SEASON_COUNT; s++) {
            cJSON *v = cJSON_GetObjectItem(seasonal, season_names[s]);
            item->seasonal_demand[s] = v != NULL ? v->valuedouble : 1.0;
        }
        i++;
    }

    cJSON *crops = cJSON_GetObjectItem(root, "crops");
    config->crop_count = (size_t)cJSON_GetArraySize(crops);
    config->crops = calloc(config->crop_count, sizeof(CropDef));
    i = 0;
    cJSON *crop_json;
    cJSON_ArrayForEach(crop_json, crops) {
        CropDef *crop = &config->crops[i++];
        crop->item_id = (ItemId)jint(crop_json, "item_id");
        crop->family = jstr(crop_json, "family");
        crop->seed_cost = jnum(crop_json, "seed_cost");
        crop->growth_days = jint(crop_json, "growth_days");
        crop->min_yield = jint(crop_json, "min_yield");
        crop->max_yield = jint(crop_json, "max_yield");
        crop->loss_chance = jnum(crop_json, "loss_chance");
        crop->water_interval_days = jint(crop_json, "water_interval_days");
        cJSON *demand = cJSON_GetObjectItem(crop_json, "nutrient_demand");
        crop->nutrient_demand.nitrogen = jnum(demand, "nitrogen");
        crop->nutrient_demand.phosphorus = jnum(demand, "phosphorus");
        crop->nutrient_demand.potassium = jnum(demand, "potassium");
        crop->unlock_requirement.type = UNLOCK_NONE;
        crop->temperature_low = jnum(crop_json, "temperature_low");
        crop->temperature_high = jnum(crop_json, "temperature_high");
        crop->ph_low = jnum(crop_json, "ph_low");
        crop->ph_high = jnum(crop_json, "ph_high");
        crop->min_moisture = jnum(crop_json, "min_moisture");
        crop->pest_susceptibility = jnum(crop_json, "pest_susceptibility");
        crop->disease_susceptibility = jnum(crop_json, "disease_susceptibility");
        crop->shelf_life_days = jint(crop_json, "shelf_life_days");
    }

    cJSON *upgrades = cJSON_GetObjectItem(root, "upgrades");
    config->upgrade_count = (size_t)cJSON_GetArraySize(upgrades);
    config->upgrades = calloc(config->upgrade_count, sizeof(UpgradeDef));
    i = 0;
    cJSON *upgrade_json;
    cJSON_ArrayForEach(upgrade_json, upgrades) {
        UpgradeDef *upgrade = &config->upgrades[i++];
        upgrade->id = (UpgradeId)jint(upgrade_json, "id");
        upgrade->external_id = jstr(upgrade_json, "external_id");
        upgrade->name = upgrade->external_id;
        upgrade->cost = jnum(upgrade_json, "cost");
        cJSON *effect = cJSON_GetObjectItem(upgrade_json, "effect");
        const char *effect_type = jstr(effect, "type");
        if (strcmp(effect_type, "growth_time_reduction") == 0) {
            upgrade->effect.type = EFFECT_GROWTH_TIME_REDUCTION;
            upgrade->effect.as.growth_time_reduction = jnum(effect, "amount");
        } else if (strcmp(effect_type, "capacity") == 0) {
            upgrade->effect.type = EFFECT_CAPACITY;
            upgrade->effect.as.capacity = jint(effect, "amount");
        } else if (strcmp(effect_type, "processing_capacity") == 0) {
            upgrade->effect.type = EFFECT_PROCESSING_CAPACITY;
            upgrade->effect.as.processing_capacity = jint(effect, "amount");
        } else if (strcmp(effect_type, "storage") == 0) {
            upgrade->effect.type = EFFECT_STORAGE;
            upgrade->effect.as.storage.capacity_bonus = jint(effect, "capacity_bonus");
            upgrade->effect.as.storage.shelf_life_multiplier = jnum(effect, "shelf_life_multiplier");
        } else {
            fprintf(stderr, "unknown upgrade effect type: %s\n", effect_type);
            exit(1);
        }
    }

    cJSON *recipes = cJSON_GetObjectItem(root, "recipes");
    config->recipe_count = (size_t)cJSON_GetArraySize(recipes);
    config->recipes = calloc(config->recipe_count, sizeof(RecipeDef));
    i = 0;
    cJSON *recipe_json;
    cJSON_ArrayForEach(recipe_json, recipes) {
        RecipeDef *recipe = &config->recipes[i++];
        recipe->id = (RecipeId)jint(recipe_json, "id");
        recipe->external_id = jstr(recipe_json, "external_id");
        recipe->input_item_id = (ItemId)jint(recipe_json, "input_item_id");
        recipe->output_item_id = (ItemId)jint(recipe_json, "output_item_id");
        recipe->input_quantity = jint(recipe_json, "input_quantity");
        recipe->output_quantity = jint(recipe_json, "output_quantity");
        recipe->processing_days = jint(recipe_json, "processing_days");
        recipe->min_quality = parse_quality(jstr(recipe_json, "min_quality"));
        recipe->cost = jnum(recipe_json, "cost");
        recipe->shelf_life_days = jint(recipe_json, "shelf_life_days");
    }

    cJSON *channels = cJSON_GetObjectItem(root, "channels");
    config->channel_count = (size_t)cJSON_GetArraySize(channels);
    config->channels = calloc(config->channel_count, sizeof(ChannelDef));
    i = 0;
    cJSON *channel_json;
    cJSON_ArrayForEach(channel_json, channels) {
        ChannelDef *channel = &config->channels[i++];
        channel->channel_id = (ChannelId)jint(channel_json, "channel_id");
        channel->external_id = jstr(channel_json, "external_id");
        channel->min_quality_rank = parse_quality(jstr(channel_json, "min_quality"));
        channel->min_reputation = jnum(channel_json, "min_reputation");
        channel->has_daily_capacity = jhas_nonnull(channel_json, "daily_capacity");
        channel->daily_capacity = jint(channel_json, "daily_capacity");
        channel->price_multiplier = jnum(channel_json, "price_multiplier");
        channel->reputation_bonus = jnum(channel_json, "reputation_bonus");
        channel->flat_fee = jnum(channel_json, "flat_fee");
        channel->fee_rate = jnum(channel_json, "fee_rate");
    }

    cJSON *buyers = cJSON_GetObjectItem(root, "buyers");
    config->buyer_count = (size_t)cJSON_GetArraySize(buyers);
    config->buyers = calloc(config->buyer_count, sizeof(BuyerDef));
    i = 0;
    cJSON *buyer_json;
    cJSON_ArrayForEach(buyer_json, buyers) {
        BuyerDef *buyer = &config->buyers[i++];
        buyer->id = (BuyerId)jint(buyer_json, "id");
        buyer->external_id = jstr(buyer_json, "external_id");
        buyer->name = buyer->external_id;
        buyer->min_reputation = jnum(buyer_json, "min_reputation");
        buyer->relationship_bonus_rate = jnum(buyer_json, "relationship_bonus_rate");
        cJSON *allowed = cJSON_GetObjectItem(buyer_json, "allowed_items");
        buyer->allowed_item_count = (size_t)cJSON_GetArraySize(allowed);
        buyer->allowed_items =
            buyer->allowed_item_count > 0 ? malloc(buyer->allowed_item_count * sizeof(ItemId)) : NULL;
        int a = 0;
        cJSON *item_id_json;
        cJSON_ArrayForEach(item_id_json, allowed) {
            buyer->allowed_items[a++] = (ItemId)item_id_json->valueint;
        }
        buyer->quantity_min = jint(buyer_json, "quantity_min");
        buyer->quantity_max = jint(buyer_json, "quantity_max");
        buyer->min_quality = parse_quality(jstr(buyer_json, "min_quality"));
        buyer->contract_price_multiplier = jnum(buyer_json, "contract_price_multiplier");
        buyer->deadline_days = jint(buyer_json, "deadline_days");
        buyer->penalty_rate = jnum(buyer_json, "penalty_rate");
    }

    cJSON *fert = cJSON_GetObjectItem(root, "fertilizer");
    config->fertilizer.cost = jnum(fert, "cost");
    config->fertilizer.loss_chance_reduction = jnum(fert, "loss_chance_reduction");
    config->fertilizer.yield_bonus_pct = jnum(fert, "yield_bonus_pct");
    config->fertilizer.quality_bonus = jnum(fert, "quality_bonus");
    cJSON *nutrients_added = cJSON_GetObjectItem(fert, "nutrients_added");
    config->fertilizer.nutrients_added.nitrogen = jnum(nutrients_added, "nitrogen");
    config->fertilizer.nutrients_added.phosphorus = jnum(nutrients_added, "phosphorus");
    config->fertilizer.nutrients_added.potassium = jnum(nutrients_added, "potassium");

    cJSON *watering = cJSON_GetObjectItem(root, "watering");
    config->watering.neglect_loss_chance_penalty_per_day =
        jnum(watering, "neglect_loss_chance_penalty_per_day");
    config->watering.neglect_yield_penalty_per_day = jnum(watering, "neglect_yield_penalty_per_day");
    config->watering.max_neglect_loss_chance_bonus = jnum(watering, "max_neglect_loss_chance_bonus");
    config->watering.max_neglect_yield_penalty = jnum(watering, "max_neglect_yield_penalty");
    config->watering.cost_per_plot = jnum(watering, "cost_per_plot");
    config->watering.moisture_added = jnum(watering, "moisture_added");

    cJSON *dyn = cJSON_GetObjectItem(root, "soil_dynamics");
    config->soil_dynamics.harvest_soil_health_cost = jnum(dyn, "harvest_soil_health_cost");
    config->soil_dynamics.min_soil_health = jnum(dyn, "min_soil_health");
    config->soil_dynamics.fallow_pest_decay = jnum(dyn, "fallow_pest_decay");
    config->soil_dynamics.fallow_disease_decay = jnum(dyn, "fallow_disease_decay");
    config->soil_dynamics.fallow_soil_health_regen = jnum(dyn, "fallow_soil_health_regen");
    config->soil_dynamics.pest_growth_per_day = jnum(dyn, "pest_growth_per_day");
    config->soil_dynamics.disease_growth_per_rainfall = jnum(dyn, "disease_growth_per_rainfall");
    config->soil_dynamics.max_pest_pressure = jnum(dyn, "max_pest_pressure");
    config->soil_dynamics.max_disease_pressure = jnum(dyn, "max_disease_pressure");
    config->soil_dynamics.same_family_yield_penalty = jnum(dyn, "same_family_yield_penalty");
    config->soil_dynamics.same_family_quality_penalty = jnum(dyn, "same_family_quality_penalty");
    config->soil_dynamics.soil_health_yield_floor = jnum(dyn, "soil_health_yield_floor");
    config->soil_dynamics.soil_health_yield_span = jnum(dyn, "soil_health_yield_span");

    cJSON *regen = cJSON_GetObjectItem(root, "plot_regen");
    config->plot_regen.moisture = jnum(regen, "moisture");
    config->plot_regen.nitrogen = jnum(regen, "nitrogen");
    config->plot_regen.phosphorus = jnum(regen, "phosphorus");
    config->plot_regen.potassium = jnum(regen, "potassium");
    config->plot_regen.soil_health = jnum(regen, "soil_health");
    config->plot_regen.pest_pressure = jnum(regen, "pest_pressure");
    config->plot_regen.disease_pressure = jnum(regen, "disease_pressure");

    cJSON *markets_json = cJSON_GetObjectItem(root, "markets");
    config->markets.minimum_supply_multiplier = jnum(markets_json, "minimum_supply_multiplier");
    config->markets.supply_decay = jnum(markets_json, "supply_decay");

    cJSON *contracts_config = cJSON_GetObjectItem(root, "contracts_config");
    config->contracts.fallback_price_multiplier = jnum(contracts_config, "fallback_price_multiplier");
    config->contracts.production_safety_factor = jnum(contracts_config, "production_safety_factor");
    config->contracts.offer_expiry_days = jint(contracts_config, "offer_expiry_days");
    config->contracts.offer_interval_days = jint(contracts_config, "offer_interval_days");
    config->contracts.default_penalty_rate = jnum(contracts_config, "default_penalty_rate");
    config->contracts.relationship_gain_per_delivery =
        jnum(contracts_config, "relationship_gain_per_delivery");
    config->contracts.relationship_loss_per_failure =
        jnum(contracts_config, "relationship_loss_per_failure");
    config->contracts.relationship_bonus_cap = jnum(contracts_config, "relationship_bonus_cap");
}

static StorageConfig load_storage(cJSON *root) {
    cJSON *storage = cJSON_GetObjectItem(root, "storage");
    return (StorageConfig){
        .daily_cost = jnum(storage, "daily_cost"),
        .capacity = jint(storage, "capacity"),
        .shelf_life_multiplier = jnum(storage, "shelf_life_multiplier"),
    };
}

/* --- element loaders --- */

static PlantedCrop load_planted(cJSON *json) {
    PlantedCrop planted = {0};
    planted.crop_item_id = (ItemId)jint(json, "crop_index");
    planted.day_planted = jint(json, "day_planted");
    planted.growth_days_required = jint(json, "growth_days_required");
    planted.last_watered_day = jint(json, "last_watered_day");
    planted.neglect_days = jint(json, "neglect_days");
    planted.fertilized = jbool(json, "fertilized");
    planted.plot_index = jint(json, "plot_index");
    planted.water_stress = jhex(json, "water_stress");
    planted.nutrient_stress = jhex(json, "nutrient_stress");
    planted.temperature_stress = jhex(json, "temperature_stress");
    planted.pest_stress = jhex(json, "pest_stress");
    planted.disease_stress = jhex(json, "disease_stress");
    planted.accrued_cost = jhex(json, "accrued_cost");
    return planted;
}

static void check_planted(const char *section, const char *name, const PlantedCrop *actual,
                           cJSON *expected) {
    report(actual->crop_item_id == (ItemId)jint(expected, "crop_index"), section, name, "crop_index");
    report(actual->day_planted == jint(expected, "day_planted"), section, name, "day_planted");
    report(actual->growth_days_required == jint(expected, "growth_days_required"), section, name,
           "growth_days_required");
    report(actual->last_watered_day == jint(expected, "last_watered_day"), section, name,
           "last_watered_day");
    report(actual->neglect_days == jint(expected, "neglect_days"), section, name, "neglect_days");
    report(actual->fertilized == jbool(expected, "fertilized"), section, name, "fertilized");
    report(actual->plot_index == jint(expected, "plot_index"), section, name, "plot_index");
    report(actual->water_stress == jhex(expected, "water_stress"), section, name, "water_stress");
    report(actual->nutrient_stress == jhex(expected, "nutrient_stress"), section, name,
           "nutrient_stress");
    report(actual->temperature_stress == jhex(expected, "temperature_stress"), section, name,
           "temperature_stress");
    report(actual->pest_stress == jhex(expected, "pest_stress"), section, name, "pest_stress");
    report(actual->disease_stress == jhex(expected, "disease_stress"), section, name,
           "disease_stress");
    report(actual->accrued_cost == jhex(expected, "accrued_cost"), section, name, "accrued_cost");
}

static void check_planted_vec(const char *section, const char *name, const PlantedCropVec *actual,
                               cJSON *expected_array) {
    int expected_count = cJSON_GetArraySize(expected_array);
    report(actual->count == (size_t)expected_count, section, name, "planted count");
    size_t n = actual->count < (size_t)expected_count ? actual->count : (size_t)expected_count;
    for (size_t i = 0; i < n; i++) {
        check_planted(section, name, &actual->data[i], cJSON_GetArrayItem(expected_array, (int)i));
    }
}

static PlotState load_plot(cJSON *json) {
    PlotState plot = {0};
    plot.moisture = jhex(json, "moisture");
    plot.nitrogen = jhex(json, "nitrogen");
    plot.phosphorus = jhex(json, "phosphorus");
    plot.potassium = jhex(json, "potassium");
    plot.ph = jhex(json, "ph");
    plot.soil_health = jhex(json, "soil_health");
    plot.pest_pressure = jhex(json, "pest_pressure");
    plot.disease_pressure = jhex(json, "disease_pressure");
    plot.previous_crop_family = jstr(json, "previous_crop_family");
    plot.planted_index = -1;
    return plot;
}

static void check_plot(const char *section, const char *name, const PlotState *actual,
                        cJSON *expected) {
    report(actual->moisture == jhex(expected, "moisture"), section, name, "moisture");
    report(actual->nitrogen == jhex(expected, "nitrogen"), section, name, "nitrogen");
    report(actual->phosphorus == jhex(expected, "phosphorus"), section, name, "phosphorus");
    report(actual->potassium == jhex(expected, "potassium"), section, name, "potassium");
    report(actual->ph == jhex(expected, "ph"), section, name, "ph");
    report(actual->soil_health == jhex(expected, "soil_health"), section, name, "soil_health");
    report(actual->pest_pressure == jhex(expected, "pest_pressure"), section, name, "pest_pressure");
    report(actual->disease_pressure == jhex(expected, "disease_pressure"), section, name,
           "disease_pressure");
    const char *expected_family = jstr(expected, "previous_crop_family");
    bool family_ok = (actual->previous_crop_family == NULL && expected_family == NULL) ||
                      (actual->previous_crop_family != NULL && expected_family != NULL &&
                       strcmp(actual->previous_crop_family, expected_family) == 0);
    report(family_ok, section, name, "previous_crop_family");
    /* plot->planted_index linkage: structural check against the paired
     * "crop" sub-object, rather than re-comparing every field a second
     * time (already checked via the top-level "planted" list). */
    cJSON *expected_crop = cJSON_GetObjectItem(expected, "crop");
    bool expects_crop = expected_crop != NULL && !cJSON_IsNull(expected_crop);
    report(expects_crop == (actual->planted_index != -1), section, name, "plot<->crop linkage");
}

static InventoryLot load_lot(cJSON *json) {
    InventoryLot lot = {0};
    lot.item_id = (ItemId)jint(json, "item_index");
    lot.quantity = jint(json, "quantity");
    lot.quality = parse_quality(jstr(json, "quality"));
    lot.produced_day = jint(json, "produced_day");
    lot.age_days = jint(json, "age_days");
    lot.shelf_life_days = jint(json, "shelf_life_days");
    lot.effective_shelf_life_days = jint(json, "effective_shelf_life_days");
    lot.unit_cost = jhex(json, "unit_cost");
    lot.item_type = strcmp(jstr(json, "item_type"), "crop") == 0 ? ITEM_CROP : ITEM_PRODUCT;
    return lot;
}

/* Inventory lot order after a mutator is not itself semantically load-
 * bearing (only the multiset of surviving lots is), so lots are matched by
 * finding an unclaimed expected entry with the same (item, quantity,
 * quality, unit_cost, produced_day) rather than requiring positional
 * equality -- avoids spurious failures from an equally-valid compaction
 * order. */
static void check_lot_vec(const char *section, const char *name, const InventoryLotVec *actual,
                           cJSON *expected_array) {
    int expected_count = cJSON_GetArraySize(expected_array);
    report(actual->count == (size_t)expected_count, section, name, "inventory_lots count");
    bool *claimed = expected_count > 0 ? calloc((size_t)expected_count, sizeof(bool)) : NULL;
    for (size_t i = 0; i < actual->count; i++) {
        const InventoryLot *lot = &actual->data[i];
        bool found = false;
        for (int j = 0; j < expected_count; j++) {
            if (claimed[j]) continue;
            cJSON *e = cJSON_GetArrayItem(expected_array, j);
            if (lot->item_id == (ItemId)jint(e, "item_index") && lot->quantity == jint(e, "quantity") &&
                lot->quality == parse_quality(jstr(e, "quality")) &&
                lot->produced_day == jint(e, "produced_day") && lot->unit_cost == jhex(e, "unit_cost")) {
                claimed[j] = true;
                found = true;
                break;
            }
        }
        report(found, section, name, "unexpected or mismatched inventory lot");
    }
    free(claimed);
}

static ProcessingJob load_job(cJSON *json) {
    return (ProcessingJob){
        .recipe_id = (RecipeId)jint(json, "recipe_index"),
        .output_item_id = (ItemId)jint(json, "output_item_index"),
        .output_quantity = jint(json, "output_quantity"),
        .completion_day = jint(json, "completion_day"),
        .shelf_life_days = jint(json, "shelf_life_days"),
        .unit_cost = jhex(json, "unit_cost"),
    };
}

static void check_job_vec(const char *section, const char *name, const ProcessingJobVec *actual,
                           cJSON *expected_array) {
    int expected_count = cJSON_GetArraySize(expected_array);
    report(actual->count == (size_t)expected_count, section, name, "processing_jobs count");
    size_t n = actual->count < (size_t)expected_count ? actual->count : (size_t)expected_count;
    for (size_t i = 0; i < n; i++) {
        cJSON *e = cJSON_GetArrayItem(expected_array, (int)i);
        const ProcessingJob *job = &actual->data[i];
        report(job->recipe_id == (RecipeId)jint(e, "recipe_index"), section, name, "recipe_index");
        report(job->output_item_id == (ItemId)jint(e, "output_item_index"), section, name,
               "output_item_index");
        report(job->output_quantity == jint(e, "output_quantity"), section, name, "output_quantity");
        report(job->completion_day == jint(e, "completion_day"), section, name, "completion_day");
        report(job->shelf_life_days == jint(e, "shelf_life_days"), section, name, "shelf_life_days");
        report(job->unit_cost == jhex(e, "unit_cost"), section, name, "unit_cost");
    }
}

static ContractRecord load_contract(cJSON *json, ContractId id) {
    return (ContractRecord){
        .id = id,
        .buyer_id = (BuyerId)jint(json, "buyer_index"),
        .item_id = (ItemId)jint(json, "item_index"),
        .quantity = jint(json, "quantity"),
        .delivered = jint(json, "delivered"),
        .min_quality = parse_quality(jstr(json, "min_quality")),
        .unit_price = jhex(json, "unit_price"),
        .penalty_rate = jhex(json, "penalty_rate"),
        .offered_day = jint(json, "offered_day"),
        .deadline_day = jint(json, "deadline_day"),
        .accepted = jbool(json, "accepted"),
        .resolved = jbool(json, "resolved"),
    };
}

static void check_contract_vec(const char *section, const char *name, const ContractVec *actual,
                                cJSON *expected_array) {
    int expected_count = cJSON_GetArraySize(expected_array);
    report(actual->count == (size_t)expected_count, section, name, "contract vec count");
    size_t n = actual->count < (size_t)expected_count ? actual->count : (size_t)expected_count;
    for (size_t i = 0; i < n; i++) {
        cJSON *e = cJSON_GetArrayItem(expected_array, (int)i);
        const ContractRecord *c = &actual->data[i];
        report(c->buyer_id == (BuyerId)jint(e, "buyer_index"), section, name, "buyer_index");
        report(c->item_id == (ItemId)jint(e, "item_index"), section, name, "item_index");
        report(c->quantity == jint(e, "quantity"), section, name, "quantity");
        report(c->delivered == jint(e, "delivered"), section, name, "delivered");
        report(c->min_quality == parse_quality(jstr(e, "min_quality")), section, name, "min_quality");
        report(c->unit_price == jhex(e, "unit_price"), section, name, "unit_price");
        report(c->penalty_rate == jhex(e, "penalty_rate"), section, name, "penalty_rate");
        report(c->offered_day == jint(e, "offered_day"), section, name, "offered_day");
        report(c->deadline_day == jint(e, "deadline_day"), section, name, "deadline_day");
        report(c->accepted == jbool(e, "accepted"), section, name, "accepted");
        report(c->resolved == jbool(e, "resolved"), section, name, "resolved");
    }
}

/* Finds the position of the contract in `array` whose recorded Python "id"
 * string equals `target`; returns INVALID_ID if not found (matching
 * Python's own "no such contract" outcome for a bogus id). */
static ContractId find_contract_id(cJSON *array, const char *target) {
    int idx = 0;
    cJSON *entry;
    cJSON_ArrayForEach(entry, array) {
        const char *id = jstr(entry, "id");
        if (id != NULL && strcmp(id, target) == 0) {
            return (ContractId)idx;
        }
        idx++;
    }
    return INVALID_ID;
}

/* --- generic player (FarmState) snapshot load/check --- */

static void scatter_int(cJSON *obj, int *values) {
    cJSON *entry;
    cJSON_ArrayForEach(entry, obj) {
        values[atoi(entry->string)] = entry->valueint;
    }
}
static void scatter_double(cJSON *obj, double *values) {
    cJSON *entry;
    cJSON_ArrayForEach(entry, obj) {
        /* Values are float.hex()-encoded strings (see jhex's header
         * comment), not JSON numbers -- valuedouble is only meaningful for
         * a cJSON_Number node, so this must go through valuestring/strtod
         * like every other hex field, not entry->valuedouble. */
        values[atoi(entry->string)] = strtod(entry->valuestring, NULL);
    }
}

static void load_player(cJSON *snapshot, const ResolvedConfig *config, FarmState *state) {
    double money = jhex(snapshot, "money");
    int slots_total = jint(snapshot, "slots_total");
    farm_state_init(state, config, money, slots_total);
    state->day = jint(snapshot, "day");

    scatter_int(cJSON_GetObjectItem(snapshot, "seed_inventory"), state->seed_inventory);
    state->fertilizer_inventory = jint(snapshot, "fertilizer_inventory");
    state->total_expenses = jhex(snapshot, "total_expenses");
    cJSON *expenses = cJSON_GetObjectItem(snapshot, "expenses_by_category");
    static const char *expense_names[EXPENSE_COUNT] = {
        "seeds", "watering", "fertilizer", "upgrades", "storage", "processing", "contract_penalties",
    };
    for (int c = 0; c < EXPENSE_COUNT; c++) {
        cJSON *v = cJSON_GetObjectItem(expenses, expense_names[c]);
        state->expenses_by_category[c] = v != NULL ? strtod(v->valuestring, NULL) : 0.0;
    }
    state->total_planted = jint(snapshot, "total_planted");
    scatter_int(cJSON_GetObjectItem(snapshot, "crop_plant_counts"), state->crop_plant_counts);

    cJSON *planted_array = cJSON_GetObjectItem(snapshot, "planted");
    cJSON *planted_json;
    cJSON_ArrayForEach(planted_json, planted_array) {
        planted_crop_vec_push(&state->planted, load_planted(planted_json));
    }

    cJSON *plots_array = cJSON_GetObjectItem(snapshot, "plots");
    int p = 0;
    cJSON *plot_json;
    cJSON_ArrayForEach(plot_json, plots_array) {
        if ((size_t)p < state->plot_count) {
            state->plots[p] = load_plot(plot_json);
        }
        p++;
    }
    /* Derive each plot's planted_index from the loaded planted vec's own
     * plot_index fields, rather than re-parsing the redundant nested
     * "crop" sub-object under each plot (see tools/export_mutation_
     * fixtures.py's serialize_plot -- plot.crop and the matching entry in
     * player.planted are literally the same Python object). */
    for (size_t i = 0; i < state->planted.count; i++) {
        int plot_index = state->planted.data[i].plot_index;
        if (plot_index >= 0 && (size_t)plot_index < state->plot_count) {
            state->plots[plot_index].planted_index = (int)i;
        }
    }

    cJSON *lots_array = cJSON_GetObjectItem(snapshot, "inventory_lots");
    cJSON *lot_json;
    cJSON_ArrayForEach(lot_json, lots_array) {
        inventory_lot_vec_push(&state->inventory_lots, load_lot(lot_json));
    }

    cJSON *jobs_array = cJSON_GetObjectItem(snapshot, "processing_jobs");
    cJSON *job_json;
    cJSON_ArrayForEach(job_json, jobs_array) {
        processing_job_vec_push(&state->processing_jobs, load_job(job_json));
    }

    cJSON *active_array = cJSON_GetObjectItem(snapshot, "active_contracts");
    int ac = 0;
    cJSON *active_json;
    cJSON_ArrayForEach(active_json, active_array) {
        contract_vec_push(&state->active_contracts, load_contract(active_json, (ContractId)ac));
        ac++;
    }
    cJSON *offers_array = cJSON_GetObjectItem(snapshot, "contract_offers");
    int oc = 0;
    cJSON *offer_json;
    cJSON_ArrayForEach(offer_json, offers_array) {
        contract_vec_push(&state->contract_offers, load_contract(offer_json, (ContractId)oc));
        oc++;
    }

    scatter_double(cJSON_GetObjectItem(snapshot, "buyer_relationships"), state->buyer_relationships);
    state->reputation = jhex(snapshot, "reputation");

    cJSON *prices = cJSON_GetObjectItem(snapshot, "market_prices");
    cJSON *price_entry;
    cJSON_ArrayForEach(price_entry, prices) {
        int idx = atoi(price_entry->string);
        state->market_prices[idx] = strtod(price_entry->valuestring, NULL);
        state->has_market_price[idx] = true;
    }
    scatter_double(cJSON_GetObjectItem(snapshot, "market_supply"), state->market_supply);
    scatter_int(cJSON_GetObjectItem(snapshot, "channel_capacity_used"), state->channel_capacity_used);

    cJSON *revenue_by_channel = cJSON_GetObjectItem(snapshot, "revenue_by_channel");
    cJSON *rev_entry;
    cJSON_ArrayForEach(rev_entry, revenue_by_channel) {
        double value = strtod(rev_entry->valuestring, NULL);
        if (strcmp(rev_entry->string, "contract") == 0) {
            state->contract_channel_revenue = value;
        } else {
            ChannelId cid = config_channel_id_by_external_id(config, rev_entry->string);
            if (id_valid(cid)) {
                state->revenue_by_channel[cid] = value;
            }
        }
    }

    state->total_revenue = jhex(snapshot, "total_revenue");
    state->total_sold = jint(snapshot, "total_sold");
    state->idle_days = jint(snapshot, "idle_days");
    state->total_waterings = jint(snapshot, "total_waterings");
    state->total_harvest_events = jint(snapshot, "total_harvest_events");
    state->total_harvested = jint(snapshot, "total_harvested");
    state->total_crops_lost = jint(snapshot, "total_crops_lost");
    state->total_fertilizer_bought = jint(snapshot, "total_fertilizer_bought");
    state->total_fertilizer_applied = jint(snapshot, "total_fertilizer_applied");
    state->total_spoiled = jint(snapshot, "total_spoiled");
    state->total_processed = jint(snapshot, "total_processed");
    state->processing_revenue = jhex(snapshot, "processing_revenue");
    state->contracts_completed = jint(snapshot, "contracts_completed");
    state->contracts_failed = jint(snapshot, "contracts_failed");
    state->contract_penalties = jhex(snapshot, "contract_penalties");

    cJSON *quality_harvested = cJSON_GetObjectItem(snapshot, "quality_harvested");
    static const char *quality_names[QUALITY_COUNT] = {"rejected", "processing", "standard",
                                                        "premium"};
    for (int q = 0; q < QUALITY_COUNT; q++) {
        cJSON *v = cJSON_GetObjectItem(quality_harvested, quality_names[q]);
        state->quality_harvested[q] = v != NULL ? v->valueint : 0;
    }
    cJSON *losses = cJSON_GetObjectItem(snapshot, "losses_by_cause");
    state->crop_loss_events = jint(losses, "crop_loss_events");
    state->rejected_quality_units = jint(losses, "rejected_quality_units");
    state->spoilage_units = jint(losses, "spoilage_units");

    state->has_highest_money = jhas_nonnull(snapshot, "highest_money");
    state->highest_money = state->has_highest_money ? jhex(snapshot, "highest_money") : 0.0;

    cJSON *upgrades_owned = cJSON_GetObjectItem(snapshot, "upgrades_owned");
    cJSON *ug;
    cJSON_ArrayForEach(ug, upgrades_owned) {
        state->upgrades_owned[ug->valueint] = true;
    }
    scatter_int(cJSON_GetObjectItem(snapshot, "upgrade_purchase_days"), state->upgrade_purchase_days);
}

static void check_player(const char *section, const char *name, const FarmState *state,
                          const ResolvedConfig *config, cJSON *expected) {
    report(state->money == jhex(expected, "money"), section, name, "money");
    report(state->slots_total == jint(expected, "slots_total"), section, name, "slots_total");
    report(state->day == jint(expected, "day"), section, name, "day");

    cJSON *seed_inventory = cJSON_GetObjectItem(expected, "seed_inventory");
    cJSON *si;
    cJSON_ArrayForEach(si, seed_inventory) {
        report(state->seed_inventory[atoi(si->string)] == si->valueint, section, name,
               "seed_inventory");
    }
    report(state->fertilizer_inventory == jint(expected, "fertilizer_inventory"), section, name,
           "fertilizer_inventory");
    report(state->total_expenses == jhex(expected, "total_expenses"), section, name, "total_expenses");
    cJSON *expenses = cJSON_GetObjectItem(expected, "expenses_by_category");
    static const char *expense_names[EXPENSE_COUNT] = {
        "seeds", "watering", "fertilizer", "upgrades", "storage", "processing", "contract_penalties",
    };
    for (int c = 0; c < EXPENSE_COUNT; c++) {
        cJSON *v = cJSON_GetObjectItem(expenses, expense_names[c]);
        double want = v != NULL ? strtod(v->valuestring, NULL) : 0.0;
        report(state->expenses_by_category[c] == want, section, name, expense_names[c]);
    }
    report(state->total_planted == jint(expected, "total_planted"), section, name, "total_planted");
    cJSON *plant_counts = cJSON_GetObjectItem(expected, "crop_plant_counts");
    cJSON *pc;
    cJSON_ArrayForEach(pc, plant_counts) {
        report(state->crop_plant_counts[atoi(pc->string)] == pc->valueint, section, name,
               "crop_plant_counts");
    }

    check_planted_vec(section, name, &state->planted, cJSON_GetObjectItem(expected, "planted"));

    cJSON *plots_array = cJSON_GetObjectItem(expected, "plots");
    int expected_plot_count = cJSON_GetArraySize(plots_array);
    report(state->plot_count == (size_t)expected_plot_count, section, name, "plot_count");
    size_t np = state->plot_count < (size_t)expected_plot_count ? state->plot_count
                                                                  : (size_t)expected_plot_count;
    for (size_t i = 0; i < np; i++) {
        check_plot(section, name, &state->plots[i], cJSON_GetArrayItem(plots_array, (int)i));
    }

    check_lot_vec(section, name, &state->inventory_lots, cJSON_GetObjectItem(expected, "inventory_lots"));
    check_job_vec(section, name, &state->processing_jobs,
                  cJSON_GetObjectItem(expected, "processing_jobs"));
    check_contract_vec(section, name, &state->active_contracts,
                        cJSON_GetObjectItem(expected, "active_contracts"));
    check_contract_vec(section, name, &state->contract_offers,
                        cJSON_GetObjectItem(expected, "contract_offers"));

    cJSON *relationships = cJSON_GetObjectItem(expected, "buyer_relationships");
    cJSON *br;
    cJSON_ArrayForEach(br, relationships) {
        report(state->buyer_relationships[atoi(br->string)] == strtod(br->valuestring, NULL), section,
               name, "buyer_relationships");
    }
    report(state->reputation == jhex(expected, "reputation"), section, name, "reputation");

    cJSON *prices = cJSON_GetObjectItem(expected, "market_prices");
    cJSON *pr;
    cJSON_ArrayForEach(pr, prices) {
        int idx = atoi(pr->string);
        report(state->has_market_price[idx] && state->market_prices[idx] == strtod(pr->valuestring, NULL),
               section, name, "market_prices");
    }
    cJSON *supply = cJSON_GetObjectItem(expected, "market_supply");
    cJSON *sp;
    cJSON_ArrayForEach(sp, supply) {
        report(state->market_supply[atoi(sp->string)] == strtod(sp->valuestring, NULL), section, name,
               "market_supply");
    }
    cJSON *capacity_used = cJSON_GetObjectItem(expected, "channel_capacity_used");
    cJSON *cu;
    cJSON_ArrayForEach(cu, capacity_used) {
        report(state->channel_capacity_used[atoi(cu->string)] == cu->valueint, section, name,
               "channel_capacity_used");
    }
    cJSON *revenue_by_channel = cJSON_GetObjectItem(expected, "revenue_by_channel");
    cJSON *rev;
    cJSON_ArrayForEach(rev, revenue_by_channel) {
        double want = strtod(rev->valuestring, NULL);
        if (strcmp(rev->string, "contract") == 0) {
            report(state->contract_channel_revenue == want, section, name, "contract_channel_revenue");
        } else {
            ChannelId cid = config_channel_id_by_external_id(config, rev->string);
            report(id_valid(cid) && state->revenue_by_channel[cid] == want, section, name,
                   "revenue_by_channel");
        }
    }

    report(state->total_revenue == jhex(expected, "total_revenue"), section, name, "total_revenue");
    report(state->total_sold == jint(expected, "total_sold"), section, name, "total_sold");
    report(state->idle_days == jint(expected, "idle_days"), section, name, "idle_days");
    report(state->total_waterings == jint(expected, "total_waterings"), section, name,
           "total_waterings");
    report(state->total_harvest_events == jint(expected, "total_harvest_events"), section, name,
           "total_harvest_events");
    report(state->total_harvested == jint(expected, "total_harvested"), section, name,
           "total_harvested");
    report(state->total_crops_lost == jint(expected, "total_crops_lost"), section, name,
           "total_crops_lost");
    report(state->total_fertilizer_bought == jint(expected, "total_fertilizer_bought"), section, name,
           "total_fertilizer_bought");
    report(state->total_fertilizer_applied == jint(expected, "total_fertilizer_applied"), section,
           name, "total_fertilizer_applied");
    report(state->total_spoiled == jint(expected, "total_spoiled"), section, name, "total_spoiled");
    report(state->total_processed == jint(expected, "total_processed"), section, name,
           "total_processed");
    report(state->processing_revenue == jhex(expected, "processing_revenue"), section, name,
           "processing_revenue");
    report(state->contracts_completed == jint(expected, "contracts_completed"), section, name,
           "contracts_completed");
    report(state->contracts_failed == jint(expected, "contracts_failed"), section, name,
           "contracts_failed");
    report(state->contract_penalties == jhex(expected, "contract_penalties"), section, name,
           "contract_penalties");

    cJSON *quality_harvested = cJSON_GetObjectItem(expected, "quality_harvested");
    static const char *quality_names[QUALITY_COUNT] = {"rejected", "processing", "standard",
                                                        "premium"};
    for (int q = 0; q < QUALITY_COUNT; q++) {
        cJSON *v = cJSON_GetObjectItem(quality_harvested, quality_names[q]);
        int want = v != NULL ? v->valueint : 0;
        report(state->quality_harvested[q] == want, section, name, quality_names[q]);
    }
    cJSON *losses = cJSON_GetObjectItem(expected, "losses_by_cause");
    report(state->crop_loss_events == jint(losses, "crop_loss_events"), section, name,
           "crop_loss_events");
    report(state->rejected_quality_units == jint(losses, "rejected_quality_units"), section, name,
           "rejected_quality_units");
    report(state->spoilage_units == jint(losses, "spoilage_units"), section, name, "spoilage_units");

    bool expect_highest = jhas_nonnull(expected, "highest_money");
    report(state->has_highest_money == expect_highest, section, name, "has_highest_money");
    if (expect_highest) {
        report(state->highest_money == jhex(expected, "highest_money"), section, name,
               "highest_money");
    }

    cJSON *upgrades_owned = cJSON_GetObjectItem(expected, "upgrades_owned");
    for (size_t u = 0; u < config->upgrade_count; u++) {
        bool want = false;
        cJSON *ug;
        cJSON_ArrayForEach(ug, upgrades_owned) {
            if ((size_t)ug->valueint == u) want = true;
        }
        report(state->upgrades_owned[u] == want, section, name, "upgrades_owned");
    }
    cJSON *purchase_days = cJSON_GetObjectItem(expected, "upgrade_purchase_days");
    cJSON *pd;
    cJSON_ArrayForEach(pd, purchase_days) {
        report(state->upgrade_purchase_days[atoi(pd->string)] == pd->valueint, section, name,
               "upgrade_purchase_days");
    }
}

/* --- case runners --- */

typedef struct {
    ResolvedConfig config;
    StorageConfig storage;
} World;

static FarmState begin_case(const World *world, cJSON *c) {
    FarmState state;
    load_player(cJSON_GetObjectItem(c, "before"), &world->config, &state);
    return state;
}

static void finish_case(const char *section, const World *world, cJSON *c, FarmState *state) {
    check_player(section, jstr(c, "name"), state, &world->config, cJSON_GetObjectItem(c, "after"));
    farm_state_destroy(state);
}

static void run_buy_seeds(World *w, cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        FarmState state = begin_case(w, c);
        cJSON *r = cJSON_GetObjectItem(c, "result");
        const CropDef *crop = config_find_crop(&w->config, (ItemId)jint(r, "crop_index"));
        bool ok = actions_buy_seeds(&state, crop, jint(r, "quantity"));
        report(ok == jbool(r, "ok"), "buy_seeds", jstr(c, "name"), "ok");
        finish_case("buy_seeds", w, c, &state);
    }
}

static void run_plant_seed(World *w, cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        FarmState state = begin_case(w, c);
        cJSON *r = cJSON_GetObjectItem(c, "result");
        const CropDef *crop = config_find_crop(&w->config, (ItemId)jint(r, "crop_index"));
        bool ok = actions_plant_seed(&state, crop, jint(r, "growth_days"), jbool(r, "fertilized"),
                                      &w->config.fertilizer);
        report(ok == jbool(r, "ok"), "plant_seed", jstr(c, "name"), "ok");
        finish_case("plant_seed", w, c, &state);
    }
}

static void run_water_crop(World *w, cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        FarmState state = begin_case(w, c);
        cJSON *r = cJSON_GetObjectItem(c, "result");
        int idx = jint(r, "planted_index");
        bool ok = actions_water_crop(&state, &state.planted.data[idx], &w->config.watering);
        report(ok == jbool(r, "ok"), "water_crop", jstr(c, "name"), "ok");
        finish_case("water_crop", w, c, &state);
    }
}

static void run_buy_fertilizer(World *w, cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        FarmState state = begin_case(w, c);
        cJSON *r = cJSON_GetObjectItem(c, "result");
        bool ok = actions_buy_fertilizer(&state, &w->config.fertilizer, jint(r, "quantity"));
        report(ok == jbool(r, "ok"), "buy_fertilizer", jstr(c, "name"), "ok");
        finish_case("buy_fertilizer", w, c, &state);
    }
}

static void run_fertilize_crop(World *w, cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        FarmState state = begin_case(w, c);
        cJSON *r = cJSON_GetObjectItem(c, "result");
        int idx = jint(r, "planted_index");
        bool ok = actions_fertilize_crop(&state, &state.planted.data[idx], &w->config.fertilizer);
        report(ok == jbool(r, "ok"), "fertilize_crop", jstr(c, "name"), "ok");
        finish_case("fertilize_crop", w, c, &state);
    }
}

static void run_harvest_mature(World *w, cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        FarmState state = begin_case(w, c);
        cJSON *r = cJSON_GetObjectItem(c, "result");
        FarmRng rng;
        rng_seed(&rng, (uint64_t)jnum(r, "seed"));
        bool harvested = actions_harvest_mature(&state, &w->config, &rng, &w->config.watering,
                                                 &w->config.fertilizer);
        report(harvested == jbool(r, "harvested"), "harvest_mature", jstr(c, "name"), "harvested");
        finish_case("harvest_mature", w, c, &state);
    }
}

static void run_buy_upgrade(World *w, cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        FarmState state = begin_case(w, c);
        cJSON *r = cJSON_GetObjectItem(c, "result");
        const UpgradeDef *upgrade = config_find_upgrade(&w->config, (UpgradeId)jint(r, "upgrade_index"));
        bool ok = actions_buy_upgrade(&state, upgrade);
        report(ok == jbool(r, "ok"), "buy_upgrade", jstr(c, "name"), "ok");
        finish_case("buy_upgrade", w, c, &state);
    }
}

static void run_do_nothing(World *w, cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        FarmState state = begin_case(w, c);
        actions_do_nothing(&state);
        finish_case("do_nothing", w, c, &state);
    }
}

static void run_consume(World *w, cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        FarmState state = begin_case(w, c);
        cJSON *r = cJSON_GetObjectItem(c, "result");
        int consumed;
        double cost;
        inventory_consume(&state, (ItemId)jint(r, "item_index"), jint(r, "quantity"),
                           parse_quality(jstr(r, "min_quality")), &consumed, &cost);
        report(consumed == jint(r, "consumed"), "consume", jstr(c, "name"), "consumed");
        report(cost == jhex(r, "cost"), "consume", jstr(c, "name"), "cost");
        finish_case("consume", w, c, &state);
    }
}

static void run_capture_storage_liability(World *w, cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        FarmState state = begin_case(w, c);
        cJSON *r = cJSON_GetObjectItem(c, "result");
        double liability = inventory_capture_storage_liability(&state, &w->storage);
        report(liability == jhex(r, "liability"), "capture_storage_liability", jstr(c, "name"),
               "liability");
        finish_case("capture_storage_liability", w, c, &state);
    }
}

static void run_collect_storage_liability(World *w, cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        FarmState state = begin_case(w, c);
        cJSON *r = cJSON_GetObjectItem(c, "result");
        double charged = inventory_collect_storage_liability(&state, jhex(r, "liability"));
        report(charged == jhex(r, "charged"), "collect_storage_liability", jstr(c, "name"), "charged");
        finish_case("collect_storage_liability", w, c, &state);
    }
}

static void run_enforce_storage_capacity(World *w, cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        FarmState state = begin_case(w, c);
        cJSON *r = cJSON_GetObjectItem(c, "result");
        int spoiled = inventory_enforce_storage_capacity(&state, jint(r, "capacity"));
        report(spoiled == jint(r, "spoiled"), "enforce_storage_capacity", jstr(c, "name"), "spoiled");
        finish_case("enforce_storage_capacity", w, c, &state);
    }
}

static void run_age_and_spoil(World *w, cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        FarmState state = begin_case(w, c);
        cJSON *r = cJSON_GetObjectItem(c, "result");
        int spoiled = inventory_age_and_spoil(&state, &w->storage, jbool(r, "charge_storage"));
        report(spoiled == jint(r, "spoiled"), "age_and_spoil", jstr(c, "name"), "spoiled");
        finish_case("age_and_spoil", w, c, &state);
    }
}

static void run_update_daily_prices(World *w, cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        FarmState state = begin_case(w, c);
        cJSON *r = cJSON_GetObjectItem(c, "result");
        state.current_season = parse_season(jstr(r, "season"));
        FarmRng rng;
        rng_seed(&rng, (uint64_t)jnum(r, "seed"));
        markets_update_daily_prices(&state, &w->config, &rng);
        cJSON *prices = cJSON_GetObjectItem(r, "prices");
        cJSON *pr;
        cJSON_ArrayForEach(pr, prices) {
            int idx = atoi(pr->string);
            report(state.has_market_price[idx] && state.market_prices[idx] == strtod(pr->valuestring, NULL),
                   "update_daily_prices", jstr(c, "name"), "price");
        }
        finish_case("update_daily_prices", w, c, &state);
    }
}

static void run_sell(World *w, cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        FarmState state = begin_case(w, c);
        cJSON *r = cJSON_GetObjectItem(c, "result");
        const ChannelDef *channel = config_find_channel(&w->config, (ChannelId)jint(r, "channel_index"));
        bool has_quality = jhas_nonnull(r, "quality");
        bool has_min_quality = jhas_nonnull(r, "min_quality");
        int sold;
        double revenue = markets_sell(&state, (ItemId)jint(r, "item_index"), jint(r, "quantity"),
                                       channel, has_quality, parse_quality(jstr(r, "quality")),
                                       has_min_quality, parse_quality(jstr(r, "min_quality")), &sold);
        report(revenue == jhex(r, "revenue"), "sell", jstr(c, "name"), "revenue");
        report(sold == jint(r, "sold"), "sell", jstr(c, "name"), "sold");
        finish_case("sell", w, c, &state);
    }
}

static void run_start_job(World *w, cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        FarmState state = begin_case(w, c);
        cJSON *r = cJSON_GetObjectItem(c, "result");
        const RecipeDef *recipe = config_find_recipe(&w->config, (RecipeId)jint(r, "recipe_index"));
        bool ok = processing_start_job(&state, recipe, jint(r, "batches"), jint(r, "capacity"));
        report(ok == jbool(r, "ok"), "start_job", jstr(c, "name"), "ok");
        finish_case("start_job", w, c, &state);
    }
}

static void run_complete_jobs(World *w, cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        FarmState state = begin_case(w, c);
        cJSON *r = cJSON_GetObjectItem(c, "result");
        int completed = processing_complete_jobs(&state);
        report(completed == jint(r, "completed"), "complete_jobs", jstr(c, "name"), "completed");
        finish_case("complete_jobs", w, c, &state);
    }
}

static void run_visible_offers(World *w, cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        FarmState state = begin_case(w, c);
        cJSON *r = cJSON_GetObjectItem(c, "result");
        ContractVec visible;
        contracts_visible_offers(&state, &w->config, NULL, &visible);
        cJSON *expected_offers = cJSON_GetObjectItem(r, "offers");
        report(visible.count == (size_t)cJSON_GetArraySize(expected_offers), "visible_offers",
               jstr(c, "name"), "count");
        size_t n = visible.count < (size_t)cJSON_GetArraySize(expected_offers)
                       ? visible.count
                       : (size_t)cJSON_GetArraySize(expected_offers);
        for (size_t i = 0; i < n; i++) {
            int expected_buyer = cJSON_GetArrayItem(expected_offers, (int)i)->valueint;
            report(visible.data[i].buyer_id == (BuyerId)expected_buyer, "visible_offers", jstr(c, "name"),
                   "buyer_id");
        }
        contract_vec_free(&visible);
        finish_case("visible_offers", w, c, &state);
    }
}

static void run_generate_offers(World *w, cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        FarmState state = begin_case(w, c);
        cJSON *r = cJSON_GetObjectItem(c, "result");
        size_t before_count = state.contract_offers.count;
        FarmRng rng;
        rng_seed(&rng, (uint64_t)jnum(r, "seed"));
        contracts_generate_offers(&state, &w->config, &rng);
        /* `visible_offers(player)` first drops resolved/expired offers, so
         * "new offers this call" isn't simply the post-call count minus the
         * pre-call one when the before-snapshot already carries some -- but
         * every generate_offers fixture scenario starts with an empty
         * contract_offers, so the simple delta is exact for these cases. */
        long delta = (long)state.contract_offers.count - (long)before_count;
        report(delta == jint(r, "new_offer_count"), "generate_offers", jstr(c, "name"),
               "new_offer_count");
        finish_case("generate_offers", w, c, &state);
    }
}

static void run_accept(World *w, cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        FarmState state = begin_case(w, c);
        cJSON *r = cJSON_GetObjectItem(c, "result");
        const char *target = jstr(r, "contract_id_target");
        cJSON *before_offers = cJSON_GetObjectItem(cJSON_GetObjectItem(c, "before"), "contract_offers");
        ContractId id = find_contract_id(before_offers, target);
        bool ok = contracts_accept(&state, &w->config, id);
        report(ok == jbool(r, "ok"), "accept", jstr(c, "name"), "ok");
        finish_case("accept", w, c, &state);
    }
}

static void run_deliver(World *w, cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        FarmState state = begin_case(w, c);
        cJSON *r = cJSON_GetObjectItem(c, "result");
        const char *target = jstr(r, "contract_id_target");
        cJSON *before_active = cJSON_GetObjectItem(cJSON_GetObjectItem(c, "before"), "active_contracts");
        ContractId id = find_contract_id(before_active, target);
        int delivered;
        double revenue = contracts_deliver(&state, &w->config, id, jint(r, "quantity"), &delivered);
        report(revenue == jhex(r, "revenue"), "deliver", jstr(c, "name"), "revenue");
        report(delivered == jint(r, "delivered"), "deliver", jstr(c, "name"), "delivered");
        finish_case("deliver", w, c, &state);
    }
}

static void run_resolve_expired(World *w, cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        FarmState state = begin_case(w, c);
        contracts_resolve_expired(&state, &w->config);
        finish_case("resolve_expired", w, c, &state);
    }
}

int main(void) {
    FILE *f = fopen("tests/fixtures/mutation.json", "rb");
    if (f == NULL) {
        fprintf(stderr, "cannot open tests/fixtures/mutation.json (run `make fixtures-mutation` "
                        "first)\n");
        return 1;
    }
    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *buf = malloc((size_t)size + 1);
    size_t read_len = fread(buf, 1, (size_t)size, f);
    buf[read_len] = '\0';
    fclose(f);

    cJSON *root = cJSON_Parse(buf);
    if (root == NULL) {
        fprintf(stderr, "failed to parse mutation.json\n");
        return 1;
    }

    World world;
    cJSON *config_json = cJSON_GetObjectItem(root, "config");
    load_config(config_json, &world.config);
    world.storage = load_storage(config_json);

    run_buy_seeds(&world, cJSON_GetObjectItem(root, "buy_seeds_cases"));
    run_plant_seed(&world, cJSON_GetObjectItem(root, "plant_seed_cases"));
    run_water_crop(&world, cJSON_GetObjectItem(root, "water_crop_cases"));
    run_buy_fertilizer(&world, cJSON_GetObjectItem(root, "buy_fertilizer_cases"));
    run_fertilize_crop(&world, cJSON_GetObjectItem(root, "fertilize_crop_cases"));
    run_harvest_mature(&world, cJSON_GetObjectItem(root, "harvest_mature_cases"));
    run_buy_upgrade(&world, cJSON_GetObjectItem(root, "buy_upgrade_cases"));
    run_do_nothing(&world, cJSON_GetObjectItem(root, "do_nothing_cases"));
    run_consume(&world, cJSON_GetObjectItem(root, "consume_cases"));
    run_capture_storage_liability(&world, cJSON_GetObjectItem(root, "capture_storage_liability_cases"));
    run_collect_storage_liability(&world, cJSON_GetObjectItem(root, "collect_storage_liability_cases"));
    run_enforce_storage_capacity(&world, cJSON_GetObjectItem(root, "enforce_storage_capacity_cases"));
    run_age_and_spoil(&world, cJSON_GetObjectItem(root, "age_and_spoil_cases"));
    run_update_daily_prices(&world, cJSON_GetObjectItem(root, "update_daily_prices_cases"));
    run_sell(&world, cJSON_GetObjectItem(root, "sell_cases"));
    run_start_job(&world, cJSON_GetObjectItem(root, "start_job_cases"));
    run_complete_jobs(&world, cJSON_GetObjectItem(root, "complete_jobs_cases"));
    run_visible_offers(&world, cJSON_GetObjectItem(root, "visible_offers_cases"));
    run_generate_offers(&world, cJSON_GetObjectItem(root, "generate_offers_cases"));
    run_accept(&world, cJSON_GetObjectItem(root, "accept_cases"));
    run_deliver(&world, cJSON_GetObjectItem(root, "deliver_cases"));
    run_resolve_expired(&world, cJSON_GetObjectItem(root, "resolve_expired_cases"));

    printf("%d checks, %d failed\n", g_checked, g_failed);

    cJSON_Delete(root);
    free(buf);
    free(world.config.crops);
    free(world.config.items);
    free(world.config.upgrades);
    free(world.config.recipes);
    free(world.config.channels);
    for (size_t i = 0; i < world.config.buyer_count; i++) {
        free(world.config.buyers[i].allowed_items);
    }
    free(world.config.buyers);

    return g_failed == 0 ? 0 : 1;
}
