/* Fixture-driven parity test for src/rng.c: loads farm-c/tests/fixtures/
 * rng.json (generated by tools/export_rng_fixtures.py, with CPython's
 * random.Random as the oracle -- see that script's header), seeds one
 * FarmRng per fixture the same way Python seeded its random.Random, replays
 * the identical fixed-order call sequence, and asserts every result matches
 * exactly. No epsilon: these are raw RNG outputs (or one arithmetic step
 * away from them), and the two languages are expected to agree bit-for-bit.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "rng.h"
#include "third_party/cJSON.h"

static int g_checked = 0;
static int g_failed = 0;

static void report(bool ok, uint64_t seed, int call_index, const char *method, const char *detail) {
    g_checked++;
    if (!ok) {
        g_failed++;
        fprintf(stderr, "FAIL  seed=%llu call=%-5d %-14s %s\n", (unsigned long long)seed, call_index,
                method, detail != NULL ? detail : "");
    }
}

static double jnum(const cJSON *obj, const char *key) {
    cJSON *item = cJSON_GetObjectItem(obj, key);
    return item != NULL ? item->valuedouble : 0.0;
}

static uint64_t jseed(const cJSON *obj, const char *key) {
    /* cJSON's valueint is a plain (32-bit) int, so seeds like 2**32 that
     * this fixture deliberately includes would truncate through it --
     * valuedouble is exact for every integer this repo's seeds use (well
     * under 2**53). */
    return (uint64_t)jnum(obj, key);
}

static const char *jstr(const cJSON *obj, const char *key) {
    cJSON *item = cJSON_GetObjectItem(obj, key);
    return (item != NULL && cJSON_IsString(item)) ? item->valuestring : NULL;
}

static bool jbool(const cJSON *obj, const char *key) {
    cJSON *item = cJSON_GetObjectItem(obj, key);
    return item != NULL && cJSON_IsTrue(item);
}

static void run_seed_fixture(const cJSON *fixture) {
    uint64_t seed = jseed(fixture, "seed");
    FarmRng rng;
    rng_seed(&rng, seed);

    const cJSON *calls = cJSON_GetObjectItem(fixture, "calls");
    int call_index = 0;
    const cJSON *call;
    cJSON_ArrayForEach(call, calls) {
        const char *method = jstr(call, "method");
        char detail[128];

        if (strcmp(method, "roll_yield") == 0) {
            int min_yield = (int)jnum(call, "min_yield");
            int max_yield = (int)jnum(call, "max_yield");
            int expected = (int)jnum(call, "expected");
            int actual = rng_roll_yield(&rng, min_yield, max_yield);
            snprintf(detail, sizeof(detail), "expected=%d actual=%d", expected, actual);
            report(actual == expected, seed, call_index, method, detail);
        } else if (strcmp(method, "roll_price") == 0) {
            double base_price = jnum(call, "base_price");
            double variation = jnum(call, "variation");
            double expected = jnum(call, "expected");
            double actual = rng_roll_price(&rng, base_price, variation);
            snprintf(detail, sizeof(detail), "expected=%.17g actual=%.17g", expected, actual);
            report(actual == expected, seed, call_index, method, detail);
        } else if (strcmp(method, "roll_loss") == 0) {
            double loss_chance = jnum(call, "loss_chance");
            bool expected = jbool(call, "expected");
            bool actual = rng_roll_loss(&rng, loss_chance);
            snprintf(detail, sizeof(detail), "expected=%d actual=%d", expected, actual);
            report(actual == expected, seed, call_index, method, detail);
        } else if (strcmp(method, "roll_watering") == 0) {
            double diligence = jnum(call, "diligence");
            bool expected = jbool(call, "expected");
            bool actual = rng_roll_watering(&rng, diligence);
            snprintf(detail, sizeof(detail), "expected=%d actual=%d", expected, actual);
            report(actual == expected, seed, call_index, method, detail);
        } else if (strcmp(method, "chance") == 0) {
            double probability = jnum(call, "probability");
            bool expected = jbool(call, "expected");
            bool actual = rng_chance(&rng, probability);
            snprintf(detail, sizeof(detail), "expected=%d actual=%d", expected, actual);
            report(actual == expected, seed, call_index, method, detail);
        } else if (strcmp(method, "uniform") == 0) {
            double minimum = jnum(call, "minimum");
            double maximum = jnum(call, "maximum");
            double expected = jnum(call, "expected");
            double actual = rng_uniform_event(&rng, minimum, maximum);
            snprintf(detail, sizeof(detail), "expected=%.17g actual=%.17g", expected, actual);
            report(actual == expected, seed, call_index, method, detail);
        } else if (strcmp(method, "choice") == 0) {
            uint32_t length = (uint32_t)jnum(call, "length");
            int expected = (int)jnum(call, "expected");
            int actual = (int)rng_choice_index(&rng, length);
            snprintf(detail, sizeof(detail), "expected=%d actual=%d", expected, actual);
            report(actual == expected, seed, call_index, method, detail);
        } else {
            fprintf(stderr, "unknown fixture method: %s\n", method);
            exit(1);
        }
        call_index++;
    }
}

int main(void) {
    FILE *f = fopen("tests/fixtures/rng.json", "rb");
    if (f == NULL) {
        fprintf(stderr, "cannot open tests/fixtures/rng.json (run `make fixtures-rng` first, "
                         "or run this binary from farm-c/)\n");
        return 1;
    }
    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *buffer = malloc((size_t)size + 1);
    size_t read = fread(buffer, 1, (size_t)size, f);
    buffer[read] = '\0';
    fclose(f);

    cJSON *root = cJSON_Parse(buffer);
    if (root == NULL) {
        fprintf(stderr, "failed to parse fixtures JSON\n");
        return 1;
    }

    const cJSON *seeds = cJSON_GetObjectItem(root, "seeds");
    const cJSON *fixture;
    cJSON_ArrayForEach(fixture, seeds) {
        run_seed_fixture(fixture);
    }

    printf("%d checks, %d failed\n", g_checked, g_failed);

    cJSON_Delete(root);
    free(buffer);

    return g_failed == 0 ? 0 : 1;
}
