/* Fixture-driven parity test for the Phase 1 physics port
 * (src/crop_growth.c, src/weather.c): loads farm-c/tests/fixtures/
 * physics.json (generated by tools/export_physics_fixtures.py, with the
 * real Python simulation/crop_growth.py and simulation/weather.py as the
 * oracle) and checks every recorded case against the C port's actual
 * output. Floats are compared with `==` (not epsilon): these are bit-exact
 * physics ports, and float.hex() round-trips through strtod exactly, so
 * any mismatch is a real divergence, not float-formatting noise.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "config.h"
#include "crop_growth.h"
#include "rng.h"
#include "state.h"
#include "third_party/cJSON.h"
#include "weather.h"

static int g_checked = 0;
static int g_failed = 0;

static void report(bool ok, const char *section, const char *name, const char *detail) {
    g_checked++;
    if (!ok) {
        g_failed++;
        fprintf(stderr, "FAIL  %-24s %-28s %s\n", section, name, detail != NULL ? detail : "");
    }
}

/* --- small cJSON helpers (same pattern as test_agents.c/test_rng.c) --- */

static double jnum(const cJSON *obj, const char *key) {
    cJSON *item = cJSON_GetObjectItem(obj, key);
    return item != NULL ? item->valuedouble : 0.0;
}
static int jint(const cJSON *obj, const char *key) {
    cJSON *item = cJSON_GetObjectItem(obj, key);
    return item != NULL ? item->valueint : 0;
}
static const char *jstr(const cJSON *obj, const char *key) {
    cJSON *item = cJSON_GetObjectItem(obj, key);
    return (item != NULL && cJSON_IsString(item)) ? item->valuestring : NULL;
}
static bool jbool(const cJSON *obj, const char *key) {
    cJSON *item = cJSON_GetObjectItem(obj, key);
    return item != NULL && cJSON_IsTrue(item);
}
static bool jhas_nonnull(const cJSON *obj, const char *key) {
    cJSON *item = cJSON_GetObjectItem(obj, key);
    return item != NULL && !cJSON_IsNull(item);
}
/* float.hex()-formatted string -> double, via C99 hex-float strtod --
 * exact, since both sides round-trip the same IEEE-754 bit pattern (see
 * tools/export_physics_fixtures.py's header comment). */
static double jhex(const cJSON *obj, const char *key) {
    const char *s = jstr(obj, key);
    if (s == NULL) {
        fprintf(stderr, "missing hex field: %s\n", key);
        exit(1);
    }
    return strtod(s, NULL);
}

static Quality parse_quality_grade(const char *s) {
    if (strcmp(s, "rejected") == 0) return QUALITY_REJECTED;
    if (strcmp(s, "processing") == 0) return QUALITY_PROCESSING;
    if (strcmp(s, "standard") == 0) return QUALITY_STANDARD;
    if (strcmp(s, "premium") == 0) return QUALITY_PREMIUM;
    fprintf(stderr, "unknown quality grade string: %s\n", s);
    exit(1);
}

static Season parse_season(const char *s) {
    if (strcmp(s, "spring") == 0) return SEASON_SPRING;
    if (strcmp(s, "summer") == 0) return SEASON_SUMMER;
    if (strcmp(s, "autumn") == 0) return SEASON_AUTUMN;
    if (strcmp(s, "winter") == 0) return SEASON_WINTER;
    fprintf(stderr, "unknown season string: %s\n", s);
    exit(1);
}

/* --- config loading --- */

static SoilDynamics parse_soil_dynamics(cJSON *dyn) {
    SoilDynamics d;
    d.harvest_soil_health_cost = jnum(dyn, "harvest_soil_health_cost");
    d.min_soil_health = jnum(dyn, "min_soil_health");
    d.fallow_pest_decay = jnum(dyn, "fallow_pest_decay");
    d.fallow_disease_decay = jnum(dyn, "fallow_disease_decay");
    d.fallow_soil_health_regen = jnum(dyn, "fallow_soil_health_regen");
    d.pest_growth_per_day = jnum(dyn, "pest_growth_per_day");
    d.disease_growth_per_rainfall = jnum(dyn, "disease_growth_per_rainfall");
    d.max_pest_pressure = jnum(dyn, "max_pest_pressure");
    d.max_disease_pressure = jnum(dyn, "max_disease_pressure");
    d.same_family_yield_penalty = jnum(dyn, "same_family_yield_penalty");
    d.same_family_quality_penalty = jnum(dyn, "same_family_quality_penalty");
    d.soil_health_yield_floor = jnum(dyn, "soil_health_yield_floor");
    d.soil_health_yield_span = jnum(dyn, "soil_health_yield_span");
    return d;
}

static PlotRegen parse_plot_regen(cJSON *regen) {
    PlotRegen r;
    r.moisture = jnum(regen, "moisture");
    r.nitrogen = jnum(regen, "nitrogen");
    r.phosphorus = jnum(regen, "phosphorus");
    r.potassium = jnum(regen, "potassium");
    r.soil_health = jnum(regen, "soil_health");
    r.pest_pressure = jnum(regen, "pest_pressure");
    r.disease_pressure = jnum(regen, "disease_pressure");
    return r;
}

static void load_config(cJSON *root, ResolvedConfig *config) {
    memset(config, 0, sizeof(*config));

    cJSON *crops = cJSON_GetObjectItem(root, "crops");
    config->crop_count = (size_t)cJSON_GetArraySize(crops);
    config->crops = calloc(config->crop_count, sizeof(CropDef));
    int i = 0;
    cJSON *crop_json;
    cJSON_ArrayForEach(crop_json, crops) {
        CropDef *crop = &config->crops[i];
        crop->item_id = (ItemId)i;
        crop->role = CROP_ROLE_OTHER;
        crop->family = jstr(crop_json, "family");
        crop->seed_cost = jnum(crop_json, "seed_cost");
        crop->growth_days = jint(crop_json, "growth_days");
        crop->min_yield = jint(crop_json, "min_yield");
        crop->max_yield = jint(crop_json, "max_yield");
        crop->loss_chance = jnum(crop_json, "loss_chance");
        crop->water_interval_days = jint(crop_json, "water_interval_days");
        cJSON *demand = cJSON_GetObjectItem(crop_json, "nutrient_demand");
        crop->nutrient_demand.nitrogen = jnum(demand, "nitrogen");
        crop->nutrient_demand.phosphorus = jnum(demand, "phosphorus");
        crop->nutrient_demand.potassium = jnum(demand, "potassium");
        crop->unlock_requirement.type = UNLOCK_NONE;

        cJSON *temp_range = cJSON_GetObjectItem(crop_json, "temperature_range");
        crop->temperature_low = cJSON_GetArrayItem(temp_range, 0)->valuedouble;
        crop->temperature_high = cJSON_GetArrayItem(temp_range, 1)->valuedouble;
        cJSON *ph_range = cJSON_GetObjectItem(crop_json, "ph_range");
        crop->ph_low = cJSON_GetArrayItem(ph_range, 0)->valuedouble;
        crop->ph_high = cJSON_GetArrayItem(ph_range, 1)->valuedouble;
        crop->min_moisture = jnum(crop_json, "min_moisture");
        crop->pest_susceptibility = jnum(crop_json, "pest_susceptibility");
        crop->disease_susceptibility = jnum(crop_json, "disease_susceptibility");
        i++;
    }

    cJSON *fert = cJSON_GetObjectItem(root, "fertilizer");
    config->fertilizer.cost = jnum(fert, "cost");
    config->fertilizer.loss_chance_reduction = jnum(fert, "loss_chance_reduction");
    config->fertilizer.yield_bonus_pct = jnum(fert, "yield_bonus_pct");
    config->fertilizer.quality_bonus = jnum(fert, "quality_bonus");

    cJSON *watering = cJSON_GetObjectItem(root, "watering");
    config->watering.neglect_loss_chance_penalty_per_day =
        jnum(watering, "neglect_loss_chance_penalty_per_day");
    config->watering.neglect_yield_penalty_per_day = jnum(watering, "neglect_yield_penalty_per_day");
    config->watering.max_neglect_loss_chance_bonus = jnum(watering, "max_neglect_loss_chance_bonus");
    config->watering.max_neglect_yield_penalty = jnum(watering, "max_neglect_yield_penalty");
    config->watering.cost_per_plot = jnum(watering, "cost_per_plot");
    config->watering.moisture_added = jnum(watering, "moisture_added");

    config->soil_dynamics = parse_soil_dynamics(cJSON_GetObjectItem(root, "soil_dynamics"));
    config->plot_regen = parse_plot_regen(cJSON_GetObjectItem(root, "plot_regen"));

    cJSON *weather_world = cJSON_GetObjectItem(root, "weather_world");
    config->weather.season_length_days = jint(weather_world, "season_length_days");
    cJSON *seasons = cJSON_GetObjectItem(weather_world, "seasons");
    static const char *season_names[SEASON_COUNT] = {"spring", "summer", "autumn", "winter"};
    for (int s = 0; s < SEASON_COUNT; s++) {
        cJSON *season_json = cJSON_GetObjectItem(seasons, season_names[s]);
        SeasonWeather *sw = &config->weather.by_season[s];
        cJSON *temp_range = cJSON_GetObjectItem(season_json, "temperature_range");
        sw->temperature_low = cJSON_GetArrayItem(temp_range, 0)->valuedouble;
        sw->temperature_high = cJSON_GetArrayItem(temp_range, 1)->valuedouble;
        sw->rain_chance = jnum(season_json, "rain_chance");
        cJSON *rain_range = cJSON_GetObjectItem(season_json, "rainfall_range");
        sw->rainfall_low = cJSON_GetArrayItem(rain_range, 0)->valuedouble;
        sw->rainfall_high = cJSON_GetArrayItem(rain_range, 1)->valuedouble;
        sw->evaporation = jnum(season_json, "evaporation");
    }
}

/* --- PlantedCrop / PlotState loading --- */

static PlantedCrop load_planted(cJSON *json) {
    PlantedCrop planted = {0};
    planted.crop_item_id = (ItemId)jint(json, "crop_index");
    planted.day_planted = jint(json, "day_planted");
    planted.growth_days_required = jint(json, "growth_days_required");
    planted.last_watered_day = jint(json, "last_watered_day");
    planted.neglect_days = jint(json, "neglect_days");
    planted.fertilized = jbool(json, "fertilized");
    planted.plot_index = -1;
    planted.water_stress = jhex(json, "water_stress");
    planted.nutrient_stress = jhex(json, "nutrient_stress");
    planted.temperature_stress = jhex(json, "temperature_stress");
    planted.pest_stress = jhex(json, "pest_stress");
    planted.disease_stress = jhex(json, "disease_stress");
    return planted;
}

static PlotState load_plot(cJSON *json) {
    PlotState plot = {0};
    plot.moisture = jhex(json, "moisture");
    plot.nitrogen = jhex(json, "nitrogen");
    plot.phosphorus = jhex(json, "phosphorus");
    plot.potassium = jhex(json, "potassium");
    plot.ph = jhex(json, "ph");
    plot.soil_health = jhex(json, "soil_health");
    plot.pest_pressure = jhex(json, "pest_pressure");
    plot.disease_pressure = jhex(json, "disease_pressure");
    plot.previous_crop_family = jstr(json, "previous_crop_family");
    plot.planted_index = -1;
    return plot;
}

static void check_planted(const char *section, const char *name, const PlantedCrop *actual,
                           cJSON *expected) {
    report(actual->water_stress == jhex(expected, "water_stress"), section, name, "water_stress");
    report(actual->nutrient_stress == jhex(expected, "nutrient_stress"), section, name,
           "nutrient_stress");
    report(actual->temperature_stress == jhex(expected, "temperature_stress"), section, name,
           "temperature_stress");
    report(actual->pest_stress == jhex(expected, "pest_stress"), section, name, "pest_stress");
    report(actual->disease_stress == jhex(expected, "disease_stress"), section, name,
           "disease_stress");
    report(actual->neglect_days == jint(expected, "neglect_days"), section, name, "neglect_days");
}

static void check_plot(const char *section, const char *name, const PlotState *actual,
                        cJSON *expected) {
    report(actual->moisture == jhex(expected, "moisture"), section, name, "moisture");
    report(actual->nitrogen == jhex(expected, "nitrogen"), section, name, "nitrogen");
    report(actual->phosphorus == jhex(expected, "phosphorus"), section, name, "phosphorus");
    report(actual->potassium == jhex(expected, "potassium"), section, name, "potassium");
    report(actual->ph == jhex(expected, "ph"), section, name, "ph");
    report(actual->soil_health == jhex(expected, "soil_health"), section, name, "soil_health");
    report(actual->pest_pressure == jhex(expected, "pest_pressure"), section, name, "pest_pressure");
    report(actual->disease_pressure == jhex(expected, "disease_pressure"), section, name,
           "disease_pressure");
}

/* --- section runners --- */

static void run_update_crop_stress(const ResolvedConfig *config, cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        const char *name = jstr(c, "name");
        int crop_index = jint(c, "crop_index");
        const CropDef *crop = &config->crops[crop_index];
        PlantedCrop planted = load_planted(cJSON_GetObjectItem(c, "before_planted"));
        PlotState plot = load_plot(cJSON_GetObjectItem(c, "before_plot"));
        double temperature = jhex(c, "temperature");
        double evaporation = jhex(c, "evaporation");

        crop_growth_update_stress(&planted, &plot, crop, temperature, evaporation);

        check_planted("update_crop_stress", name, &planted, cJSON_GetObjectItem(c, "after_planted"));
        check_plot("update_crop_stress", name, &plot, cJSON_GetObjectItem(c, "after_plot"));
    }
}

static void run_harvest_multipliers(const ResolvedConfig *config, cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        const char *name = jstr(c, "name");
        int crop_index = jint(c, "crop_index");
        const CropDef *crop = &config->crops[crop_index];
        PlantedCrop planted = load_planted(cJSON_GetObjectItem(c, "planted"));
        cJSON *plot_json = cJSON_GetObjectItem(c, "plot");
        PlotState plot;
        bool has_plot = jhas_nonnull(c, "plot");
        if (has_plot) {
            plot = load_plot(plot_json);
        }

        double out_yield, out_quality;
        crop_growth_harvest_multipliers(&planted, crop, has_plot ? &plot : NULL, &config->fertilizer,
                                         &config->soil_dynamics, &out_yield, &out_quality);

        report(out_yield == jhex(c, "expected_yield_multiplier"), "harvest_multipliers", name,
               "yield_multiplier");
        report(out_quality == jhex(c, "expected_quality_multiplier"), "harvest_multipliers", name,
               "quality_multiplier");
    }
}

static void run_quality_grade(cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        double score = jhex(c, "score");
        Quality expected = parse_quality_grade(jstr(c, "expected_grade"));
        Quality actual = crop_growth_quality_grade(score);
        report(actual == expected, "quality_grade", jstr(c, "score"), "grade mismatch");
    }
}

static void run_harvest_outcome(const ResolvedConfig *config, cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        const char *name = jstr(c, "name");
        int crop_index = jint(c, "crop_index");
        const CropDef *crop = &config->crops[crop_index];
        PlantedCrop planted = load_planted(cJSON_GetObjectItem(c, "planted"));
        cJSON *plot_json = cJSON_GetObjectItem(c, "plot");
        PlotState plot;
        bool has_plot = jhas_nonnull(c, "plot");
        if (has_plot) {
            plot = load_plot(plot_json);
        }
        uint64_t seed = (uint64_t)jnum(c, "seed");
        FarmRng rng;
        rng_seed(&rng, seed);

        int out_yield = -1;
        bool lost = crop_growth_compute_harvest_outcome(&planted, crop, &config->watering,
                                                          &config->fertilizer, &rng,
                                                          has_plot ? &plot : NULL,
                                                          &config->soil_dynamics, &out_yield);

        report(lost == jbool(c, "expected_lost"), "harvest_outcome", name, "lost");
        report(out_yield == jint(c, "expected_yield"), "harvest_outcome", name, "yield");
    }
}

static void run_season(cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        int day = jint(c, "day");
        int season_length = jint(c, "season_length_days");
        Season expected = parse_season(jstr(c, "expected_season"));
        Season actual = weather_season_for_day(day, season_length);
        report(actual == expected, "season_for_day", jstr(c, "expected_season"), "season mismatch");
    }
}

static void run_generate_weather(const ResolvedConfig *config, cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        uint64_t seed = (uint64_t)jnum(c, "seed");
        int day = jint(c, "day");
        FarmRng rng;
        rng_seed(&rng, seed);

        WeatherDay result = weather_generate(day, config, &rng);

        Season expected_season = parse_season(jstr(c, "expected_season"));
        report(result.season == expected_season, "generate_weather", jstr(c, "expected_season"),
               "season");
        report(result.temperature == jhex(c, "expected_temperature"), "generate_weather",
               jstr(c, "expected_season"), "temperature");
        report(result.rainfall == jhex(c, "expected_rainfall"), "generate_weather",
               jstr(c, "expected_season"), "rainfall");
        report(result.evaporation == jhex(c, "expected_evaporation"), "generate_weather",
               jstr(c, "expected_season"), "evaporation");
    }
}

static void run_apply_weather(const ResolvedConfig *config, cJSON *cases) {
    cJSON *c;
    cJSON_ArrayForEach(c, cases) {
        const char *name = jstr(c, "name");
        int day = jint(c, "day");
        cJSON *weather_json = cJSON_GetObjectItem(c, "weather");
        WeatherDay weather = {0};
        weather.temperature = jhex(weather_json, "temperature");
        weather.rainfall = jhex(weather_json, "rainfall");
        weather.evaporation = jhex(weather_json, "evaporation");

        cJSON *before = cJSON_GetObjectItem(c, "before");
        int plot_count = cJSON_GetArraySize(before);

        PlotState *plots = calloc((size_t)plot_count, sizeof(PlotState));
        PlantedCropVec planted_vec = {0};

        for (int i = 0; i < plot_count; i++) {
            cJSON *plot_json = cJSON_GetArrayItem(before, i);
            plots[i] = load_plot(plot_json);
            cJSON *crop_json = cJSON_GetObjectItem(plot_json, "crop");
            if (crop_json != NULL && !cJSON_IsNull(crop_json)) {
                PlantedCrop planted = load_planted(crop_json);
                planted_crop_vec_push(&planted_vec, planted);
                plots[i].planted_index = (int)planted_vec.count - 1;
            } else {
                plots[i].planted_index = -1;
            }
        }

        /* Each case may override plot_regen/soil_dynamics (see
         * tools/export_physics_fixtures.py's "no_rain_no_regen" case, which
         * zeroes regen to isolate the no-regen path) -- a shallow copy of
         * `config` with just those two fields swapped, rather than a global
         * config shared across every case. */
        ResolvedConfig case_config = *config;
        case_config.plot_regen = parse_plot_regen(cJSON_GetObjectItem(c, "plot_regen"));
        case_config.soil_dynamics = parse_soil_dynamics(cJSON_GetObjectItem(c, "soil_dynamics"));

        FarmState state = {0};
        state.config = &case_config;
        state.day = day;
        state.plots = plots;
        state.plot_count = (size_t)plot_count;
        state.planted = planted_vec;

        weather_apply(&state, &weather);

        cJSON *after = cJSON_GetObjectItem(c, "after");
        for (int i = 0; i < plot_count; i++) {
            cJSON *expected_plot = cJSON_GetArrayItem(after, i);
            check_plot("apply_weather", name, &state.plots[i], expected_plot);
            cJSON *expected_crop = cJSON_GetObjectItem(expected_plot, "crop");
            if (expected_crop != NULL && !cJSON_IsNull(expected_crop)) {
                const PlantedCrop *planted = &state.planted.data[state.plots[i].planted_index];
                check_planted("apply_weather", name, planted, expected_crop);
            }
        }

        planted_crop_vec_free(&state.planted);
        free(plots);
    }
}

int main(void) {
    FILE *f = fopen("tests/fixtures/physics.json", "rb");
    if (f == NULL) {
        fprintf(stderr, "cannot open tests/fixtures/physics.json (run `make fixtures-physics` "
                        "first)\n");
        return 1;
    }
    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *buf = malloc((size_t)size + 1);
    size_t read_len = fread(buf, 1, (size_t)size, f);
    buf[read_len] = '\0';
    fclose(f);

    cJSON *root = cJSON_Parse(buf);
    if (root == NULL) {
        fprintf(stderr, "failed to parse physics.json\n");
        return 1;
    }

    ResolvedConfig config;
    load_config(root, &config);

    run_update_crop_stress(&config, cJSON_GetObjectItem(root, "update_crop_stress_cases"));
    run_harvest_multipliers(&config, cJSON_GetObjectItem(root, "harvest_multipliers_cases"));
    run_quality_grade(cJSON_GetObjectItem(root, "quality_grade_cases"));
    run_harvest_outcome(&config, cJSON_GetObjectItem(root, "harvest_outcome_cases"));
    run_season(cJSON_GetObjectItem(root, "season_cases"));
    run_generate_weather(&config, cJSON_GetObjectItem(root, "generate_weather_cases"));
    run_apply_weather(&config, cJSON_GetObjectItem(root, "apply_weather_cases"));

    printf("%d checks, %d failed\n", g_checked, g_failed);

    cJSON_Delete(root);
    free(buf);
    free(config.crops);

    return g_failed == 0 ? 0 : 1;
}
